export class HumanError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "HumanError";
    this.code = code;
  }
}

export const HumanErrorCodes = {
  INVALID_ACTION: "INVALID_ACTION",
  MISSING_ID: "MISSING_ID",
  INVALID_GIVEN_NAME: "INVALID_GIVEN_NAME",
  INVALID_FAMILY_NAME: "INVALID_FAMILY_NAME",
  INVALID_PREFERRED_NAME: "INVALID_PREFERRED_NAME",
  INVALID_GENDER: "INVALID_GENDER",
  INVALID_BIRTH_DATE: "INVALID_BIRTH_DATE",
  INVALID_BIRTH_LOCATION_ID: "INVALID_BIRTH_LOCATION_ID",
  INVALID_NATIONALITY_COUNTRY_ID: "INVALID_NATIONALITY_COUNTRY_ID",
  INVALID_HEIGHT_CM: "INVALID_HEIGHT_CM",
  INVALID_WEIGHT_KG: "INVALID_WEIGHT_KG",
  HUMAN_NOT_FOUND: "HUMAN_NOT_FOUND",
  BIRTH_LOCATION_NOT_FOUND: "BIRTH_LOCATION_NOT_FOUND",
  NATIONALITY_COUNTRY_NOT_FOUND: "NATIONALITY_COUNTRY_NOT_FOUND",
} as const;
