import type {
  TennisTournamentSeedEntry,
  TennisTournamentVenueRef,
} from "./tennis-tour-seed.types";

type AtpTournamentVenueRef = TennisTournamentVenueRef;

type AtpTournamentSeedEntry = TennisTournamentSeedEntry & {
  venues: readonly AtpTournamentVenueRef[];
};

const DEFAULT_ATP_ACTIVE_COURT_COUNT = 12;

const MASTERS_1000 = {
  typicalDurationDays: 10,
  activeCourtCount: 14,
  drawSize: 96,
} as const;

const ATP_500 = {
  typicalDurationDays: 7,
  activeCourtCount: DEFAULT_ATP_ACTIVE_COURT_COUNT,
  drawSize: 48,
} as const;

const ATP_250 = {
  typicalDurationDays: 7,
  activeCourtCount: 8,
  drawSize: 28,
} as const;

const ranked = (minAtpRank: number) => ({
  kind: "ranked" as const,
  minAtpRank,
});

function venue(
  locationName: string,
  locationCountry: string,
  venueName: string,
  locationRegion?: string | null,
): readonly AtpTournamentVenueRef[] {
  return [
    {
      locationName,
      locationCountry,
      locationRegion,
      venueName,
      isDefault: true,
    },
  ];
}

/** Phase 4 — venue-backed ATP calendar (Masters, 500s, 250s). Slams live in atp-tour.data.ts. */
export const ATP_TOUR_CATALOG_SEED_DATA: readonly AtpTournamentSeedEntry[] = [
  {
    slug: "adelaide-international",
    name: "Adelaide International",
    isMajor: false,
    prizeMoneyUsd: 650_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 1,
    seasonStartDay: 5,
    sortOrder: 5,
    ...ATP_250,
    venues: venue("Adelaide", "Australia", "Memorial Drive Tennis Centre"),
  },
  {
    slug: "rotterdam-open",
    name: "ABN AMRO Open",
    isMajor: false,
    prizeMoneyUsd: 2_000_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 3,
    sortOrder: 6,
    ...ATP_500,
    activeCourtCount: 8,
    venues: venue("Rotterdam", "Netherlands", "Ahoy Rotterdam"),
  },
  {
    slug: "delray-beach-open",
    name: "Delray Beach Open",
    isMajor: false,
    prizeMoneyUsd: 680_000,
    entryCriteria: ranked(75),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 10,
    sortOrder: 7,
    ...ATP_250,
    venues: venue(
      "Delray Beach",
      "United States",
      "Delray Beach Tennis Center",
      "Florida",
    ),
  },
  {
    slug: "acapulco-open",
    name: "Abierto Mexicano Telcel",
    isMajor: false,
    prizeMoneyUsd: 2_200_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 24,
    sortOrder: 8,
    ...ATP_500,
    activeCourtCount: 6,
    venues: venue("Acapulco", "Mexico", "Arena GNP Seguros"),
  },
  {
    slug: "indian-wells",
    name: "BNP Paribas Open",
    isMajor: false,
    prizeMoneyUsd: 9_000_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 5,
    sortOrder: 9,
    ...MASTERS_1000,
    venues: venue(
      "Indian Wells",
      "United States",
      "Indian Wells Tennis Garden",
      "California",
    ),
  },
  {
    slug: "miami-open",
    name: "Miami Open",
    isMajor: false,
    prizeMoneyUsd: 8_800_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 19,
    sortOrder: 10,
    ...MASTERS_1000,
    venues: venue(
      "Miami",
      "United States",
      "Hard Rock Stadium Tennis Center",
      "Florida",
    ),
  },
  {
    slug: "monte-carlo-masters",
    name: "Monte-Carlo Masters",
    isMajor: false,
    prizeMoneyUsd: 6_500_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 6,
    sortOrder: 11,
    ...MASTERS_1000,
    activeCourtCount: 11,
    venues: venue("Monte Carlo", "Monaco", "Monte Carlo Country Club"),
  },
  {
    slug: "estoril-open",
    name: "Millennium Estoril Open",
    isMajor: false,
    prizeMoneyUsd: 700_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 20,
    sortOrder: 12,
    ...ATP_250,
    activeCourtCount: 7,
    venues: venue("Estoril", "Portugal", "Estoril Court Central"),
  },
  {
    slug: "madrid-open",
    name: "Mutua Madrid Open",
    isMajor: false,
    prizeMoneyUsd: 8_800_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 23,
    sortOrder: 13,
    ...MASTERS_1000,
    venues: venue("Madrid", "Spain", "Caja Magica"),
  },
  {
    slug: "rome-masters",
    name: "Internazionali BNL d'Italia",
    isMajor: false,
    prizeMoneyUsd: 7_800_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 7,
    sortOrder: 14,
    ...MASTERS_1000,
    venues: venue("Rome", "Italy", "Foro Italico"),
  },
  {
    slug: "geneva-open",
    name: "Geneva Open",
    isMajor: false,
    prizeMoneyUsd: 680_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 18,
    sortOrder: 15,
    ...ATP_250,
    activeCourtCount: 7,
    venues: venue("Geneva", "Switzerland", "Tennis Club de Geneve"),
  },
  {
    slug: "stuttgart-open",
    name: "Boss Open",
    isMajor: false,
    prizeMoneyUsd: 800_000,
    entryCriteria: ranked(75),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 9,
    sortOrder: 16,
    ...ATP_250,
    venues: venue("Stuttgart", "Germany", "Porsche Arena"),
  },
  {
    slug: "halle-open",
    name: "Terra Wortmann Open",
    isMajor: false,
    prizeMoneyUsd: 1_500_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 16,
    sortOrder: 17,
    ...ATP_500,
    activeCourtCount: 10,
    venues: venue("Halle", "Germany", "OWL Arena"),
  },
  {
    slug: "eastbourne-open",
    name: "Eastbourne Open",
    isMajor: false,
    prizeMoneyUsd: 850_000,
    entryCriteria: ranked(75),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 23,
    sortOrder: 18,
    ...ATP_250,
    venues: venue(
      "Eastbourne",
      "United Kingdom",
      "Devonshire Park Lawn Tennis Club",
      "England",
    ),
  },
  {
    slug: "bastad-open",
    name: "Nordea Open",
    isMajor: false,
    prizeMoneyUsd: 650_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 14,
    sortOrder: 19,
    ...ATP_250,
    activeCourtCount: 6,
    venues: venue("Bastad", "Sweden", "Bastad Tennis Stadium"),
  },
  {
    slug: "kitzbuhel-open",
    name: "Generali Open",
    isMajor: false,
    prizeMoneyUsd: 600_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 21,
    sortOrder: 20,
    ...ATP_250,
    activeCourtCount: 4,
    venues: venue("Kitzbuhel", "Austria", "Kitzbuhel Tennis Stadium"),
  },
  {
    slug: "los-cabos-open",
    name: "Los Cabos Open",
    isMajor: false,
    prizeMoneyUsd: 900_000,
    entryCriteria: ranked(75),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 28,
    sortOrder: 21,
    ...ATP_250,
    activeCourtCount: 6,
    venues: venue("Los Cabos", "Mexico", "Los Cabos Tennis Open Venue"),
  },
  {
    slug: "canadian-open",
    name: "National Bank Open",
    isMajor: false,
    prizeMoneyUsd: 6_500_000,
    entryCriteria: ranked(50),
    venueMode: "rotation",
    seasonStartMonth: 8,
    seasonStartDay: 4,
    rotationEpochYear: 2024,
    sortOrder: 22,
    ...MASTERS_1000,
    activeCourtCount: 12,
    venues: [
      {
        locationName: "Toronto",
        locationCountry: "Canada",
        venueName: "Aviva Centre",
        rotationOrder: 0,
        isDefault: true,
      },
      {
        locationName: "Montreal",
        locationCountry: "Canada",
        venueName: "IGA Stadium",
        rotationOrder: 1,
      },
    ],
  },
  {
    slug: "cincinnati-masters",
    name: "Cincinnati Open",
    isMajor: false,
    prizeMoneyUsd: 6_800_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 11,
    sortOrder: 23,
    ...MASTERS_1000,
    venues: venue(
      "Cincinnati",
      "United States",
      "Lindner Family Tennis Center",
      "Ohio",
    ),
  },
  {
    slug: "shanghai-masters",
    name: "Rolex Shanghai Masters",
    isMajor: false,
    prizeMoneyUsd: 9_500_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 6,
    sortOrder: 24,
    ...MASTERS_1000,
    venues: venue("Shanghai", "China", "Qizhong Forest Sports City Arena"),
  },
  {
    slug: "basel-open",
    name: "Swiss Indoors Basel",
    isMajor: false,
    prizeMoneyUsd: 2_500_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 20,
    sortOrder: 25,
    ...ATP_500,
    activeCourtCount: 8,
    venues: venue("Basel", "Switzerland", "St. Jakobshalle"),
  },
  {
    slug: "hamburg-open",
    name: "Hamburg European Open",
    isMajor: false,
    prizeMoneyUsd: 1_200_000,
    entryCriteria: ranked(75),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 7,
    sortOrder: 26,
    ...ATP_500,
    venues: venue("Hamburg", "Germany", "Am Rothenbaum"),
  },
] as const;

export const ATP_TOUR_CATALOG_EXPECTED = {
  masters1000Count: 8,
  atp500Count: 5,
  atp250Count: 9,
  rotationCount: 1,
} as const;
