import type { CountrySeedEntry } from "./types";

type CountrySeedTuple = readonly [name: string, isoCode: string, languages: string[]];

/**
 * 200 sovereign states and territories with ISO 3166-1 alpha-2 codes.
 * Includes all 193 UN member states plus Vatican City, Palestine, Taiwan,
 * Kosovo, Hong Kong, Macau, and Western Sahara.
 */
const COUNTRY_SEED_TUPLES: readonly CountrySeedTuple[] = [
  // A
  ["Afghanistan", "AF", ["Pashto", "Dari"]],
  ["Albania", "AL", ["Albanian"]],
  ["Algeria", "DZ", ["Arabic", "Berber"]],
  ["Andorra", "AD", ["Catalan"]],
  ["Angola", "AO", ["Portuguese"]],
  ["Antigua and Barbuda", "AG", ["English"]],
  ["Argentina", "AR", ["Spanish"]],
  ["Armenia", "AM", ["Armenian"]],
  ["Australia", "AU", ["English"]],
  ["Austria", "AT", ["German"]],
  ["Azerbaijan", "AZ", ["Azerbaijani"]],
  // B
  ["Bahamas", "BS", ["English"]],
  ["Bahrain", "BH", ["Arabic"]],
  ["Bangladesh", "BD", ["Bengali"]],
  ["Barbados", "BB", ["English"]],
  ["Belarus", "BY", ["Belarusian", "Russian"]],
  ["Belgium", "BE", ["Dutch", "French", "German"]],
  ["Belize", "BZ", ["English"]],
  ["Benin", "BJ", ["French"]],
  ["Bhutan", "BT", ["Dzongkha"]],
  ["Bolivia", "BO", ["Spanish", "Quechua", "Aymara"]],
  ["Bosnia and Herzegovina", "BA", ["Bosnian", "Croatian", "Serbian"]],
  ["Botswana", "BW", ["English", "Setswana"]],
  ["Brazil", "BR", ["Portuguese"]],
  ["Brunei", "BN", ["Malay"]],
  ["Bulgaria", "BG", ["Bulgarian"]],
  ["Burkina Faso", "BF", ["French"]],
  ["Burundi", "BI", ["Kirundi", "French"]],
  // C
  ["Cabo Verde", "CV", ["Portuguese"]],
  ["Cambodia", "KH", ["Khmer"]],
  ["Cameroon", "CM", ["French", "English"]],
  ["Canada", "CA", ["English", "French"]],
  ["Central African Republic", "CF", ["French", "Sango"]],
  ["Chad", "TD", ["French", "Arabic"]],
  ["Chile", "CL", ["Spanish"]],
  ["China", "CN", ["Mandarin Chinese"]],
  ["Colombia", "CO", ["Spanish"]],
  ["Comoros", "KM", ["Comorian", "Arabic", "French"]],
  ["Congo", "CG", ["French"]],
  ["Costa Rica", "CR", ["Spanish"]],
  ["Croatia", "HR", ["Croatian"]],
  ["Cuba", "CU", ["Spanish"]],
  ["Cyprus", "CY", ["Greek", "Turkish"]],
  ["Czech Republic", "CZ", ["Czech"]],
  // D
  ["Democratic Republic of the Congo", "CD", ["French"]],
  ["Denmark", "DK", ["Danish"]],
  ["Djibouti", "DJ", ["French", "Arabic"]],
  ["Dominica", "DM", ["English"]],
  ["Dominican Republic", "DO", ["Spanish"]],
  // E
  ["Ecuador", "EC", ["Spanish"]],
  ["Egypt", "EG", ["Arabic"]],
  ["El Salvador", "SV", ["Spanish"]],
  ["Equatorial Guinea", "GQ", ["Spanish", "French", "Portuguese"]],
  ["Eritrea", "ER", ["Tigrinya", "Arabic", "English"]],
  ["Estonia", "EE", ["Estonian"]],
  ["Eswatini", "SZ", ["Swati", "English"]],
  ["Ethiopia", "ET", ["Amharic"]],
  // F
  ["Fiji", "FJ", ["English", "Fijian", "Hindi"]],
  ["Finland", "FI", ["Finnish", "Swedish"]],
  ["France", "FR", ["French"]],
  // G
  ["Gabon", "GA", ["French"]],
  ["Gambia", "GM", ["English"]],
  ["Georgia", "GE", ["Georgian"]],
  ["Germany", "DE", ["German"]],
  ["Ghana", "GH", ["English"]],
  ["Greece", "GR", ["Greek"]],
  ["Grenada", "GD", ["English"]],
  ["Guatemala", "GT", ["Spanish"]],
  ["Guinea", "GN", ["French"]],
  ["Guinea-Bissau", "GW", ["Portuguese"]],
  ["Guyana", "GY", ["English"]],
  // H
  ["Haiti", "HT", ["French", "Haitian Creole"]],
  ["Honduras", "HN", ["Spanish"]],
  ["Hong Kong", "HK", ["Cantonese", "English"]],
  ["Hungary", "HU", ["Hungarian"]],
  // I
  ["Iceland", "IS", ["Icelandic"]],
  ["India", "IN", ["Hindi", "English"]],
  ["Indonesia", "ID", ["Indonesian"]],
  ["Iran", "IR", ["Persian"]],
  ["Iraq", "IQ", ["Arabic", "Kurdish"]],
  ["Ireland", "IE", ["English", "Irish"]],
  ["Israel", "IL", ["Hebrew", "Arabic"]],
  ["Italy", "IT", ["Italian"]],
  ["Ivory Coast", "CI", ["French"]],
  // J
  ["Jamaica", "JM", ["English"]],
  ["Japan", "JP", ["Japanese"]],
  ["Jordan", "JO", ["Arabic"]],
  // K
  ["Kazakhstan", "KZ", ["Kazakh", "Russian"]],
  ["Kenya", "KE", ["Swahili", "English"]],
  ["Kiribati", "KI", ["English", "Gilbertese"]],
  ["Kosovo", "XK", ["Albanian", "Serbian"]],
  ["Kuwait", "KW", ["Arabic"]],
  ["Kyrgyzstan", "KG", ["Kyrgyz", "Russian"]],
  // L
  ["Laos", "LA", ["Lao"]],
  ["Latvia", "LV", ["Latvian"]],
  ["Lebanon", "LB", ["Arabic"]],
  ["Lesotho", "LS", ["Sesotho", "English"]],
  ["Liberia", "LR", ["English"]],
  ["Libya", "LY", ["Arabic"]],
  ["Liechtenstein", "LI", ["German"]],
  ["Lithuania", "LT", ["Lithuanian"]],
  ["Luxembourg", "LU", ["Luxembourgish", "French", "German"]],
  // M
  ["Macau", "MO", ["Cantonese", "Portuguese"]],
  ["Madagascar", "MG", ["Malagasy", "French"]],
  ["Malawi", "MW", ["English", "Chichewa"]],
  ["Malaysia", "MY", ["Malay"]],
  ["Maldives", "MV", ["Dhivehi"]],
  ["Mali", "ML", ["French"]],
  ["Malta", "MT", ["Maltese", "English"]],
  ["Marshall Islands", "MH", ["Marshallese", "English"]],
  ["Mauritania", "MR", ["Arabic"]],
  ["Mauritius", "MU", ["English", "French"]],
  ["Mexico", "MX", ["Spanish"]],
  ["Micronesia", "FM", ["English"]],
  ["Moldova", "MD", ["Romanian"]],
  ["Monaco", "MC", ["French"]],
  ["Mongolia", "MN", ["Mongolian"]],
  ["Montenegro", "ME", ["Montenegrin"]],
  ["Morocco", "MA", ["Arabic", "Berber"]],
  ["Mozambique", "MZ", ["Portuguese"]],
  ["Myanmar", "MM", ["Burmese"]],
  // N
  ["Namibia", "NA", ["English"]],
  ["Nauru", "NR", ["Nauruan", "English"]],
  ["Nepal", "NP", ["Nepali"]],
  ["Netherlands", "NL", ["Dutch"]],
  ["New Zealand", "NZ", ["English", "Maori"]],
  ["Nicaragua", "NI", ["Spanish"]],
  ["Niger", "NE", ["French"]],
  ["Nigeria", "NG", ["English"]],
  ["North Korea", "KP", ["Korean"]],
  ["North Macedonia", "MK", ["Macedonian"]],
  ["Norway", "NO", ["Norwegian"]],
  // O
  ["Oman", "OM", ["Arabic"]],
  // P
  ["Pakistan", "PK", ["Urdu", "English"]],
  ["Palau", "PW", ["Palauan", "English"]],
  ["Palestine", "PS", ["Arabic"]],
  ["Panama", "PA", ["Spanish"]],
  ["Papua New Guinea", "PG", ["English", "Tok Pisin", "Hiri Motu"]],
  ["Paraguay", "PY", ["Spanish", "Guarani"]],
  ["Peru", "PE", ["Spanish", "Quechua"]],
  ["Philippines", "PH", ["Filipino", "English"]],
  ["Poland", "PL", ["Polish"]],
  ["Portugal", "PT", ["Portuguese"]],
  // Q
  ["Qatar", "QA", ["Arabic"]],
  // R
  ["Romania", "RO", ["Romanian"]],
  ["Russia", "RU", ["Russian"]],
  ["Rwanda", "RW", ["Kinyarwanda", "French", "English"]],
  // S
  ["Saint Kitts and Nevis", "KN", ["English"]],
  ["Saint Lucia", "LC", ["English"]],
  ["Saint Vincent and the Grenadines", "VC", ["English"]],
  ["Samoa", "WS", ["Samoan", "English"]],
  ["San Marino", "SM", ["Italian"]],
  ["São Tomé and Príncipe", "ST", ["Portuguese"]],
  ["Saudi Arabia", "SA", ["Arabic"]],
  ["Senegal", "SN", ["French"]],
  ["Serbia", "RS", ["Serbian"]],
  ["Seychelles", "SC", ["Seychellois Creole", "English", "French"]],
  ["Sierra Leone", "SL", ["English"]],
  ["Singapore", "SG", ["English", "Mandarin Chinese", "Malay", "Tamil"]],
  ["Slovakia", "SK", ["Slovak"]],
  ["Slovenia", "SI", ["Slovenian"]],
  ["Solomon Islands", "SB", ["English"]],
  ["Somalia", "SO", ["Somali", "Arabic"]],
  ["South Africa", "ZA", ["Zulu", "Xhosa", "Afrikaans", "English"]],
  ["South Korea", "KR", ["Korean"]],
  ["South Sudan", "SS", ["English"]],
  ["Spain", "ES", ["Spanish"]],
  ["Sri Lanka", "LK", ["Sinhala", "Tamil"]],
  ["Sudan", "SD", ["Arabic", "English"]],
  ["Suriname", "SR", ["Dutch"]],
  ["Sweden", "SE", ["Swedish"]],
  ["Switzerland", "CH", ["German", "French", "Italian", "Romansh"]],
  ["Syria", "SY", ["Arabic"]],
  // T
  ["Taiwan", "TW", ["Mandarin Chinese"]],
  ["Tajikistan", "TJ", ["Tajik"]],
  ["Tanzania", "TZ", ["Swahili", "English"]],
  ["Thailand", "TH", ["Thai"]],
  ["Timor-Leste", "TL", ["Portuguese", "Tetum"]],
  ["Togo", "TG", ["French"]],
  ["Tonga", "TO", ["Tongan", "English"]],
  ["Trinidad and Tobago", "TT", ["English"]],
  ["Tunisia", "TN", ["Arabic"]],
  ["Turkey", "TR", ["Turkish"]],
  ["Turkmenistan", "TM", ["Turkmen"]],
  ["Tuvalu", "TV", ["Tuvaluan", "English"]],
  // U
  ["Uganda", "UG", ["English", "Swahili"]],
  ["Ukraine", "UA", ["Ukrainian"]],
  ["United Arab Emirates", "AE", ["Arabic"]],
  ["United Kingdom", "GB", ["English"]],
  ["United States", "US", ["English"]],
  ["Uruguay", "UY", ["Spanish"]],
  ["Uzbekistan", "UZ", ["Uzbek"]],
  // V
  ["Vanuatu", "VU", ["Bislama", "English", "French"]],
  ["Vatican City", "VA", ["Italian", "Latin"]],
  ["Venezuela", "VE", ["Spanish"]],
  ["Vietnam", "VN", ["Vietnamese"]],
  // W
  ["Western Sahara", "EH", ["Arabic"]],
  // Y
  ["Yemen", "YE", ["Arabic"]],
  // Z
  ["Zambia", "ZM", ["English"]],
  ["Zimbabwe", "ZW", ["English", "Shona", "Ndebele"]],
] as const;

export const COUNTRY_SEED_DATA: readonly CountrySeedEntry[] =
  COUNTRY_SEED_TUPLES.map(([name, isoCode, languages]) => ({
    name,
    isoCode,
    languages,
  }));
