import type { GolfTournamentSeedEntry, GolfTournamentVenueRef } from "./golf-tour-seed.types";
import { DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT } from "./golf-venue-types";

export type DpWorldTournamentSeedEntry = GolfTournamentSeedEntry & {
  venues: readonly GolfTournamentVenueRef[];
};

export const DP_WORLD_TOUR_SEED = {
  name: "DP World Tour",
  abbreviation: "DPWT",
} as const;

export const DEFAULT_DP_WORLD_TEE_GROUP_COUNT = DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT;
export const DEFAULT_DP_WORLD_FIELD_SIZE = 156;

/** Co-sanctioned with PGA Tour — reuse PGA season materialization. */
const pgaScheduleReference = (tournamentSlug: string) => ({
  scheduleReference: {
    tourAbbreviation: "PGA",
    tournamentSlug,
  },
});

const pgaMajorReference = pgaScheduleReference;

const ranked = (minOfficialWorldGolfRank: number) => ({
  kind: "ranked" as const,
  minOfficialWorldGolfRank,
});

function venue(
  locationName: string,
  locationCountry: string,
  venueName: string,
  locationRegion?: string | null,
): readonly GolfTournamentVenueRef[] {
  return [
    {
      locationName,
      locationCountry,
      locationRegion,
      venueName,
      isDefault: true,
    },
  ];
}

/** 2025 DP World Tour Race to Dubai calendar (42 events; excludes Team Cup and Ryder Cup). */
export const DP_WORLD_TOURNAMENT_SEED_DATA: readonly DpWorldTournamentSeedEntry[] = [
  {
    slug: "bmw-australian-pga-championship",
    name: "BMW Australian PGA Championship",
    isMajor: false,
    purseUsd: 1_750_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 11,
    seasonStartDay: 21,
    sortOrder: 1,
    venues: venue("Brisbane", "Australia", "Royal Queensland Golf Club"),
  },
  {
    slug: "isps-handa-australian-open",
    name: "ISPS HANDA Australian Open",
    isMajor: false,
    purseUsd: 1_750_000,
    entryCriteria: ranked(125),
    venueMode: "rotation",
    seasonStartMonth: 11,
    seasonStartDay: 28,
    rotationEpochYear: 2020,
    sortOrder: 2,
    venues: [
      {
        locationName: "Melbourne",
        locationCountry: "Australia",
        venueName: "Kingston Heath Golf Club",
        rotationOrder: 0,
        isDefault: true,
      },
      {
        locationName: "Melbourne",
        locationCountry: "Australia",
        venueName: "Victoria Golf Club",
        rotationOrder: 1,
      },
      {
        locationName: "Melbourne",
        locationCountry: "Australia",
        venueName: "Royal Melbourne Golf Club",
        rotationOrder: 2,
      },
      {
        locationName: "Sydney",
        locationCountry: "Australia",
        venueName: "The Lakes Golf Club",
        rotationOrder: 3,
      },
    ],
  },
  {
    slug: "nedbank-golf-challenge",
    name: "Nedbank Golf Challenge",
    isMajor: false,
    purseUsd: 6_000_000,
    entryCriteria: ranked(70),
    venueMode: "fixed",
    seasonStartMonth: 12,
    seasonStartDay: 5,
    sortOrder: 3,
    venues: venue("Sun City", "South Africa", "Gary Player Country Club"),
  },
  {
    slug: "alfred-dunhill-championship",
    name: "Alfred Dunhill Championship",
    isMajor: false,
    purseUsd: 1_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 12,
    seasonStartDay: 12,
    sortOrder: 4,
    venues: venue("Malelane", "South Africa", "Leopard Creek Country Club"),
  },
  {
    slug: "afrasia-bank-mauritius-open",
    name: "AfrAsia Bank Mauritius Open",
    isMajor: false,
    purseUsd: 1_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 12,
    seasonStartDay: 19,
    sortOrder: 5,
    venues: venue("Grand Baie", "Mauritius", "Mont Choisy Le Golf"),
  },
  {
    slug: "hero-dubai-desert-classic",
    name: "Hero Dubai Desert Classic",
    isMajor: false,
    purseUsd: 9_000_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 1,
    seasonStartDay: 16,
    sortOrder: 6,
    venues: venue("Dubai", "United Arab Emirates", "Emirates Golf Club"),
  },
  {
    slug: "ras-al-khaimah-championship",
    name: "Ras Al Khaimah Championship",
    isMajor: false,
    purseUsd: 2_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 1,
    seasonStartDay: 23,
    sortOrder: 7,
    venues: venue("Ras Al Khaimah", "United Arab Emirates", "Al Hamra Golf Course"),
  },
  {
    slug: "bapco-energies-bahrain-championship",
    name: "Bapco Energies Bahrain Championship",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 1,
    seasonStartDay: 30,
    sortOrder: 8,
    venues: venue("Manama", "Bahrain", "Royal Golf Club"),
  },
  {
    slug: "commercial-bank-qatar-masters",
    name: "Commercial Bank Qatar Masters",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 6,
    sortOrder: 9,
    venues: venue("Doha", "Qatar", "Doha Golf Club"),
  },
  {
    slug: "magical-kenya-open",
    name: "Magical Kenya Open",
    isMajor: false,
    purseUsd: 1_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 20,
    sortOrder: 10,
    venues: venue("Nairobi", "Kenya", "Muthaiga Golf Club"),
  },
  {
    slug: "investec-south-african-open",
    name: "Investec South African Open Championship",
    isMajor: false,
    purseUsd: 1_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 27,
    sortOrder: 11,
    venues: venue("Durban", "South Africa", "Durban Country Club"),
  },
  {
    slug: "joburg-open",
    name: "Joburg Open",
    isMajor: false,
    purseUsd: 1_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 6,
    sortOrder: 12,
    venues: venue("Johannesburg", "South Africa", "Houghton Golf Club"),
  },
  {
    slug: "porsche-singapore-classic",
    name: "Porsche Singapore Classic",
    isMajor: false,
    purseUsd: 2_500_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 20,
    sortOrder: 13,
    venues: venue("Singapore", "Singapore", "Laguna National Golf Resort Club"),
  },
  {
    slug: "hero-indian-open",
    name: "Hero Indian Open",
    isMajor: false,
    purseUsd: 2_250_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 27,
    sortOrder: 14,
    venues: venue("New Delhi", "India", "DLF Golf and Country Club"),
  },
  {
    slug: "the-masters",
    name: "The Masters Tournament",
    isMajor: true,
    ...pgaMajorReference("masters"),
    purseUsd: 20_000_000,
    entryCriteria: {
      kind: "exemptions",
      description: "Masters invitation and qualifying exemptions",
      exemptionCodes: ["masters_invite"],
    },
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 10,
    sortOrder: 15,
    venues: venue("Augusta", "United States", "Augusta National Golf Club", "Georgia"),
  },
  {
    slug: "volvo-china-open",
    name: "Volvo China Open",
    isMajor: false,
    purseUsd: 2_100_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 17,
    sortOrder: 16,
    venues: venue("Hainan", "China", "Jian Lake Blue Bay Golf Club"),
  },
  {
    slug: "hainan-classic",
    name: "Hainan Classic",
    isMajor: false,
    purseUsd: 1_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 24,
    sortOrder: 17,
    venues: venue("Hainan", "China", "Jian Lake Blue Bay Golf Club"),
  },
  {
    slug: "turkish-open",
    name: "Turkish Open",
    isMajor: false,
    purseUsd: 2_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 8,
    sortOrder: 18,
    venues: venue("Antalya", "Turkey", "Regnum Carya Golf Resort"),
  },
  {
    slug: "us-pga-championship",
    name: "U.S. PGA Championship",
    isMajor: true,
    ...pgaMajorReference("pga-championship"),
    purseUsd: 19_000_000,
    entryCriteria: { kind: "open", description: "PGA Championship qualifying field" },
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 15,
    sortOrder: 19,
    venues: venue("Charlotte", "United States", "Quail Hollow Club", "North Carolina"),
  },
  {
    slug: "soudal-open",
    name: "Soudal Open",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 22,
    sortOrder: 20,
    venues: venue("Antwerp", "Belgium", "Rinkven International Golf Club"),
  },
  {
    slug: "austrian-alpine-open",
    name: "Austrian Alpine Open presented by SalzburgerLand",
    isMajor: false,
    purseUsd: 1_750_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 29,
    sortOrder: 21,
    venues: venue("Salzburg", "Austria", "Gut Altentann Golf Club"),
  },
  {
    slug: "klm-open",
    name: "KLM Open",
    isMajor: false,
    purseUsd: 2_250_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 5,
    sortOrder: 22,
    venues: venue("Amsterdam", "Netherlands", "The International"),
  },
  {
    slug: "us-open",
    name: "U.S. Open",
    isMajor: true,
    ...pgaMajorReference("us-open"),
    purseUsd: 21_500_000,
    entryCriteria: { kind: "open", description: "Open qualifying and exemptions" },
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 12,
    sortOrder: 23,
    venues: venue("Oakmont", "United States", "Oakmont Country Club", "Pennsylvania"),
  },
  {
    slug: "italian-open",
    name: "Italian Open",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 26,
    sortOrder: 24,
    venues: venue("Monte Argentario", "Italy", "Argentario Golf Club"),
  },
  {
    slug: "bmw-international-open",
    name: "BMW International Open",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 3,
    sortOrder: 25,
    venues: venue("Munich", "Germany", "Golfclub München Eichenried"),
  },
  {
    slug: "genesis-scottish-open",
    name: "Genesis Scottish Open",
    isMajor: false,
    ...pgaScheduleReference("scottish-open"),
    purseUsd: 9_000_000,
    entryCriteria: ranked(70),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 10,
    sortOrder: 26,
    venues: venue("North Berwick", "United Kingdom", "The Renaissance Club", "Scotland"),
  },
  {
    slug: "isco-championship",
    name: "ISCO Championship",
    isMajor: false,
    purseUsd: 1_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 10,
    sortOrder: 27,
    venues: venue("Louisville", "United States", "Hurstbourne Country Club", "Kentucky"),
  },
  {
    slug: "the-open-championship",
    name: "The Open Championship",
    isMajor: true,
    ...pgaMajorReference("the-open-championship"),
    purseUsd: 16_500_000,
    entryCriteria: { kind: "open", description: "Open qualifying and exemptions" },
    venueMode: "rotation",
    seasonStartMonth: 7,
    seasonStartDay: 17,
    rotationEpochYear: 2020,
    sortOrder: 28,
    venues: [
      {
        locationName: "Portrush",
        locationCountry: "United Kingdom",
        locationRegion: "Northern Ireland",
        venueName: "Royal Portrush Dunluce Links",
        rotationOrder: 0,
        isDefault: true,
      },
      {
        locationName: "St Andrews",
        locationCountry: "United Kingdom",
        locationRegion: "Scotland",
        venueName: "St Andrews Old Course",
        rotationOrder: 1,
      },
      {
        locationName: "Troon",
        locationCountry: "United Kingdom",
        locationRegion: "Scotland",
        venueName: "Royal Troon Golf Club",
        rotationOrder: 2,
      },
    ],
  },
  {
    slug: "barracuda-championship",
    name: "Barracuda Championship",
    isMajor: false,
    purseUsd: 1_500_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 17,
    sortOrder: 29,
    venues: venue("Truckee", "United States", "Tahoe Mountain Club", "California"),
  },
  {
    slug: "dd-real-czech-masters",
    name: "D+D REAL Czech Masters",
    isMajor: false,
    purseUsd: 1_750_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 7,
    sortOrder: 30,
    venues: venue("Prague", "Czech Republic", "Albatross Golf Resort"),
  },
  {
    slug: "danish-golf-championship",
    name: "Danish Golf Championship",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 14,
    sortOrder: 31,
    venues: venue("Copenhagen", "Denmark", "Furesø Golf Klub"),
  },
  {
    slug: "betfred-british-masters",
    name: "Betfred British Masters hosted by Sir Nick Faldo",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 21,
    sortOrder: 32,
    venues: venue("Sutton Coldfield", "United Kingdom", "The Belfry", "England"),
  },
  {
    slug: "omega-european-masters",
    name: "Omega European Masters",
    isMajor: false,
    purseUsd: 3_500_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 28,
    sortOrder: 33,
    venues: venue("Crans-Montana", "Switzerland", "Crans-sur-Sierre Golf Club"),
  },
  {
    slug: "amgen-irish-open",
    name: "Amgen Irish Open",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 9,
    seasonStartDay: 4,
    sortOrder: 34,
    venues: venue("Kildare", "Ireland", "The K Club"),
  },
  {
    slug: "bmw-pga-championship",
    name: "BMW PGA Championship",
    isMajor: false,
    purseUsd: 9_000_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 9,
    seasonStartDay: 11,
    sortOrder: 35,
    venues: venue("Wentworth", "United Kingdom", "Wentworth Club West Course", "England"),
  },
  {
    slug: "fedex-open-de-france",
    name: "FedEx Open de France",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 9,
    seasonStartDay: 18,
    sortOrder: 36,
    venues: venue("Saint-Nom-la-Bretèche", "France", "Golf de Saint-Nom-la-Bretèche"),
  },
  {
    slug: "alfred-dunhill-links-championship",
    name: "Alfred Dunhill Links Championship",
    isMajor: false,
    purseUsd: 9_000_000,
    entryCriteria: ranked(70),
    venueMode: "rotation",
    seasonStartMonth: 10,
    seasonStartDay: 2,
    rotationEpochYear: 2020,
    sortOrder: 37,
    venues: [
      {
        locationName: "St Andrews",
        locationCountry: "United Kingdom",
        locationRegion: "Scotland",
        venueName: "St Andrews Old Course",
        rotationOrder: 0,
        isDefault: true,
      },
      {
        locationName: "Carnoustie",
        locationCountry: "United Kingdom",
        locationRegion: "Scotland",
        venueName: "Carnoustie Golf Links",
        rotationOrder: 1,
      },
      {
        locationName: "St Andrews",
        locationCountry: "United Kingdom",
        locationRegion: "Scotland",
        venueName: "Kingsbarns Golf Links",
        rotationOrder: 2,
      },
      {
        locationName: "Gullane",
        locationCountry: "United Kingdom",
        locationRegion: "Scotland",
        venueName: "Gullane Golf Club No. 1",
        rotationOrder: 3,
      },
      {
        locationName: "Leven",
        locationCountry: "United Kingdom",
        locationRegion: "Scotland",
        venueName: "Dumbarnie Links",
        rotationOrder: 4,
      },
      {
        locationName: "Aberdeen",
        locationCountry: "United Kingdom",
        locationRegion: "Scotland",
        venueName: "Royal Aberdeen Golf Club",
        rotationOrder: 5,
      },
    ],
  },
  {
    slug: "acciona-open-de-espana",
    name: "acciona Open de España presented by Madrid",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 9,
    sortOrder: 38,
    venues: venue("Madrid", "Spain", "Club de Campo Villa de Madrid"),
  },
  {
    slug: "dp-world-india-championship",
    name: "DP World India Championship",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(125),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 16,
    sortOrder: 39,
    venues: venue("New Delhi", "India", "DLF Golf and Country Club"),
  },
  {
    slug: "genesis-championship",
    name: "Genesis Championship",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 23,
    sortOrder: 40,
    venues: venue("Cheonan", "South Korea", "Woo Jeong Hills Country Club"),
  },
  {
    slug: "abu-dhabi-championship",
    name: "Abu Dhabi Championship",
    isMajor: false,
    purseUsd: 9_000_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 11,
    seasonStartDay: 6,
    sortOrder: 41,
    venues: venue("Abu Dhabi", "United Arab Emirates", "Yas Links"),
  },
  {
    slug: "dp-world-tour-championship",
    name: "DP World Tour Championship",
    isMajor: false,
    purseUsd: 10_000_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 11,
    seasonStartDay: 13,
    sortOrder: 42,
    venues: venue("Dubai", "United Arab Emirates", "Jumeirah Golf Estates Earth Course"),
  },
] as const;
