import {
  DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  type GolfVenueSeedEntry,
} from "./golf-venue-types";

/** DP World Tour venues (merged into the shared golf venue catalog on DP World seed). */
export const DP_WORLD_VENUE_SEED_DATA: readonly GolfVenueSeedEntry[] = [
  {
    locationName: "Brisbane",
    locationCountry: "Australia",
    venueName: "Royal Queensland Golf Club",
    latitude: -27.4256,
    longitude: 153.0619,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Melbourne",
    locationCountry: "Australia",
    venueName: "Kingston Heath Golf Club",
    latitude: -37.9786,
    longitude: 145.0658,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Melbourne",
    locationCountry: "Australia",
    venueName: "Victoria Golf Club",
    latitude: -37.9972,
    longitude: 145.0167,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Sun City",
    locationCountry: "South Africa",
    venueName: "Gary Player Country Club",
    latitude: -25.3408,
    longitude: 27.0974,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Malelane",
    locationCountry: "South Africa",
    venueName: "Leopard Creek Country Club",
    latitude: -25.4747,
    longitude: 31.5283,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Grand Baie",
    locationCountry: "Mauritius",
    venueName: "Mont Choisy Le Golf",
    latitude: -20.0134,
    longitude: 57.5806,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Abu Dhabi",
    locationCountry: "United Arab Emirates",
    venueName: "Abu Dhabi Golf Club",
    latitude: 24.4211,
    longitude: 54.475,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Dubai",
    locationCountry: "United Arab Emirates",
    venueName: "Emirates Golf Club",
    latitude: 25.1193,
    longitude: 55.1856,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Ras Al Khaimah",
    locationCountry: "United Arab Emirates",
    venueName: "Al Hamra Golf Course",
    latitude: 25.6789,
    longitude: 55.7892,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Manama",
    locationCountry: "Bahrain",
    venueName: "Royal Golf Club",
    latitude: 26.0425,
    longitude: 50.5139,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Doha",
    locationCountry: "Qatar",
    venueName: "Doha Golf Club",
    latitude: 25.3722,
    longitude: 51.4917,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Nairobi",
    locationCountry: "Kenya",
    venueName: "Muthaiga Golf Club",
    latitude: -1.2347,
    longitude: 36.8444,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Durban",
    locationCountry: "South Africa",
    venueName: "Durban Country Club",
    latitude: -29.825,
    longitude: 31.0361,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Johannesburg",
    locationCountry: "South Africa",
    venueName: "Houghton Golf Club",
    latitude: -26.1458,
    longitude: 28.0583,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Singapore",
    locationCountry: "Singapore",
    venueName: "Laguna National Golf Resort Club",
    latitude: 1.3278,
    longitude: 103.9472,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "New Delhi",
    locationCountry: "India",
    venueName: "DLF Golf and Country Club",
    latitude: 28.4431,
    longitude: 77.1028,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Hainan",
    locationCountry: "China",
    venueName: "Jian Lake Blue Bay Golf Club",
    latitude: 18.2528,
    longitude: 109.5119,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Antalya",
    locationCountry: "Turkey",
    venueName: "Regnum Carya Golf Resort",
    latitude: 36.8561,
    longitude: 31.0556,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Antwerp",
    locationCountry: "Belgium",
    venueName: "Rinkven International Golf Club",
    latitude: 51.2833,
    longitude: 4.5833,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Salzburg",
    locationCountry: "Austria",
    venueName: "Gut Altentann Golf Club",
    latitude: 47.8095,
    longitude: 13.055,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Amsterdam",
    locationCountry: "Netherlands",
    venueName: "The International",
    latitude: 52.3056,
    longitude: 4.7167,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Monte Argentario",
    locationCountry: "Italy",
    venueName: "Argentario Golf Club",
    latitude: 42.4375,
    longitude: 11.1206,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Munich",
    locationCountry: "Germany",
    venueName: "Golfclub München Eichenried",
    latitude: 48.0833,
    longitude: 11.9667,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Truckee",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "Tahoe Mountain Club",
    latitude: 39.328,
    longitude: -120.1833,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Prague",
    locationCountry: "Czech Republic",
    venueName: "Albatross Golf Resort",
    latitude: 50.0755,
    longitude: 14.4378,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Copenhagen",
    locationCountry: "Denmark",
    venueName: "Furesø Golf Klub",
    latitude: 55.8333,
    longitude: 12.3833,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Sutton Coldfield",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "The Belfry",
    latitude: 52.5648,
    longitude: -1.8243,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Kildare",
    locationCountry: "Ireland",
    venueName: "The K Club",
    latitude: 53.1561,
    longitude: -6.9094,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Saint-Nom-la-Bretèche",
    locationCountry: "France",
    venueName: "Golf de Saint-Nom-la-Bretèche",
    latitude: 48.8422,
    longitude: 2.1994,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Madrid",
    locationCountry: "Spain",
    venueName: "Club de Campo Villa de Madrid",
    latitude: 40.4431,
    longitude: -3.7611,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "St Andrews",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Kingsbarns Golf Links",
    latitude: 56.2833,
    longitude: -2.65,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Cheonan",
    locationCountry: "South Korea",
    venueName: "Woo Jeong Hills Country Club",
    latitude: 36.8151,
    longitude: 127.1139,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Abu Dhabi",
    locationCountry: "United Arab Emirates",
    venueName: "Yas Links",
    latitude: 24.4889,
    longitude: 54.6056,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Dubai",
    locationCountry: "United Arab Emirates",
    venueName: "Jumeirah Golf Estates Earth Course",
    latitude: 25.0333,
    longitude: 55.1833,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
] as const;
