import {
  DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  type GolfVenueSeedEntry,
} from "./golf-venue-types";

/** Professional golf multi_resource venues (tee groups). Shared by PGA, future LPGA, and DP World catalog seeds. */
export const GOLF_VENUE_SEED_DATA: readonly GolfVenueSeedEntry[] = [
// Golf majors and flagship courses (full 55-group field)
  {
    locationName: "Augusta",
    locationCountry: "United States",
    locationRegion: "Georgia",
    venueName: "Augusta National Golf Club",
    latitude: 33.5021,
    longitude: -82.0228,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Pinehurst",
    locationCountry: "United States",
    locationRegion: "North Carolina",
    venueName: "Pinehurst No. 2",
    latitude: 35.1954,
    longitude: -79.4695,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Pebble Beach",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "Pebble Beach Golf Links",
    latitude: 36.5674,
    longitude: -121.9487,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Ponte Vedra Beach",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "TPC Sawgrass",
    latitude: 30.1975,
    longitude: -81.3859,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Palm Beach Gardens",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "PGA National Champion Course",
    latitude: 26.8234,
    longitude: -80.1386,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "La Quinta",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "PGA West Stadium Course",
    latitude: 33.6634,
    longitude: -116.278,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Lahaina",
    locationCountry: "United States",
    locationRegion: "Hawaii",
    venueName: "Kapalua Plantation Course",
    latitude: 20.9983,
    longitude: -156.6542,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Scottsdale",
    locationCountry: "United States",
    locationRegion: "Arizona",
    venueName: "TPC Scottsdale Stadium Course",
    latitude: 33.6424,
    longitude: -111.9085,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Brookline",
    locationCountry: "United States",
    locationRegion: "Massachusetts",
    venueName: "The Country Club",
    latitude: 42.3318,
    longitude: -71.1212,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Southampton",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "Shinnecock Hills Golf Club",
    latitude: 40.8843,
    longitude: -72.3895,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Oakmont",
    locationCountry: "United States",
    locationRegion: "Pennsylvania",
    venueName: "Oakmont Country Club",
    latitude: 40.5217,
    longitude: -79.8417,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Kiawah Island",
    locationCountry: "United States",
    locationRegion: "South Carolina",
    venueName: "Kiawah Island Ocean Course",
    latitude: 32.6082,
    longitude: -80.0848,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Rochester",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "Oak Hill Country Club",
    latitude: 43.1566,
    longitude: -77.6088,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Farmingdale",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "Bethpage Black Course",
    latitude: 40.7446,
    longitude: -73.4658,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Sheboygan",
    locationCountry: "United States",
    locationRegion: "Wisconsin",
    venueName: "Whistling Straits",
    latitude: 43.8436,
    longitude: -87.7308,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "St Andrews",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "St Andrews Old Course",
    latitude: 56.3398,
    longitude: -2.7967,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Troon",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Royal Troon Golf Club",
    latitude: 55.5415,
    longitude: -4.6599,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Carnoustie",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Carnoustie Golf Links",
    latitude: 56.5026,
    longitude: -2.7059,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Gullane",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Gullane Golf Club No. 1",
    latitude: 56.035,
    longitude: -2.8284,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Southport",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Royal Birkdale Golf Club",
    latitude: 53.6476,
    longitude: -3.0053,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Hoylake",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Royal Liverpool Golf Club",
    latitude: 53.3908,
    longitude: -3.1806,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Sandwich",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Royal St George's Golf Club",
    latitude: 51.272,
    longitude: 1.3378,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Wentworth",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Wentworth Club West Course",
    latitude: 51.383,
    longitude: -0.663,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Portrush",
    locationCountry: "United Kingdom",
    locationRegion: "Northern Ireland",
    venueName: "Royal Portrush Dunluce Links",
    latitude: 55.1958,
    longitude: -6.6533,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Crans-Montana",
    locationCountry: "Switzerland",
    venueName: "Crans-sur-Sierre Golf Club",
    latitude: 46.3088,
    longitude: 7.4756,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Adare",
    locationCountry: "Ireland",
    venueName: "Adare Manor Golf Club",
    latitude: 52.5642,
    longitude: -8.7909,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },

  // PGA Tour signature & designated venues (Phase A)
  {
    locationName: "Pacific Palisades",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "Riviera Country Club",
    latitude: 34.0497,
    longitude: -118.5012,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Palm Harbor",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Innisbrook Resort Copperhead Course",
    latitude: 28.0781,
    longitude: -82.7637,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Orlando",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Bay Hill Club & Lodge",
    latitude: 28.4583,
    longitude: -81.5089,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Houston",
    locationCountry: "United States",
    locationRegion: "Texas",
    venueName: "Memorial Park Golf Course",
    latitude: 29.7671,
    longitude: -95.4342,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "San Antonio",
    locationCountry: "United States",
    locationRegion: "Texas",
    venueName: "TPC San Antonio Oaks Course",
    latitude: 29.4241,
    longitude: -98.4936,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Hilton Head Island",
    locationCountry: "United States",
    locationRegion: "South Carolina",
    venueName: "Harbour Town Golf Links",
    latitude: 32.141,
    longitude: -80.7934,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Charlotte",
    locationCountry: "United States",
    locationRegion: "North Carolina",
    venueName: "Quail Hollow Club",
    latitude: 35.1085,
    longitude: -80.8487,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Avondale",
    locationCountry: "United States",
    locationRegion: "Louisiana",
    venueName: "TPC Louisiana",
    latitude: 29.9127,
    longitude: -90.2031,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Fort Worth",
    locationCountry: "United States",
    locationRegion: "Texas",
    venueName: "Colonial Country Club",
    latitude: 32.7248,
    longitude: -97.3628,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Dublin",
    locationCountry: "United States",
    locationRegion: "Ohio",
    venueName: "Muirfield Village Golf Club",
    latitude: 40.0992,
    longitude: -83.1141,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Cromwell",
    locationCountry: "United States",
    locationRegion: "Connecticut",
    venueName: "TPC River Highlands",
    latitude: 41.5951,
    longitude: -72.6454,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Toronto",
    locationCountry: "Canada",
    venueName: "St George's Golf and Country Club",
    latitude: 43.6532,
    longitude: -79.5322,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "North Berwick",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "The Renaissance Club",
    latitude: 56.058,
    longitude: -2.7169,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Silvis",
    locationCountry: "United States",
    locationRegion: "Illinois",
    venueName: "TPC Deere Run",
    latitude: 41.5123,
    longitude: -90.4151,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Detroit",
    locationCountry: "United States",
    locationRegion: "Michigan",
    venueName: "Detroit Golf Club",
    latitude: 42.3314,
    longitude: -83.0458,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Greensboro",
    locationCountry: "United States",
    locationRegion: "North Carolina",
    venueName: "Sedgefield Country Club",
    latitude: 36.0726,
    longitude: -79.792,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },

  // PGA Tour weekly & fall swing venues (Phase B)
  {
    locationName: "Honolulu",
    locationCountry: "United States",
    locationRegion: "Hawaii",
    venueName: "Waialae Country Club",
    latitude: 21.2729,
    longitude: -157.7756,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "San Diego",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "Torrey Pines Golf Course",
    latitude: 32.9002,
    longitude: -117.2521,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Nuevo Vallarta",
    locationCountry: "Mexico",
    venueName: "Vidanta Vallarta",
    latitude: 20.9943,
    longitude: -105.3033,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Rio Grande",
    locationCountry: "United States",
    locationRegion: "Puerto Rico",
    venueName: "Grand Reserve Golf Club",
    latitude: 18.3808,
    longitude: -65.8314,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Punta Cana",
    locationCountry: "Dominican Republic",
    venueName: "Corales Golf Course",
    latitude: 18.5601,
    longitude: -68.3725,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Myrtle Beach",
    locationCountry: "United States",
    locationRegion: "South Carolina",
    venueName: "Dunes Golf and Beach Club",
    latitude: 33.6891,
    longitude: -78.8867,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Louisville",
    locationCountry: "United States",
    locationRegion: "Kentucky",
    venueName: "Hurstbourne Country Club",
    latitude: 38.2527,
    longitude: -85.7585,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "McKinney",
    locationCountry: "United States",
    locationRegion: "Texas",
    venueName: "TPC Craig Ranch",
    latitude: 33.1972,
    longitude: -96.6398,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Incline Village",
    locationCountry: "United States",
    locationRegion: "Nevada",
    venueName: "Edgewood Tahoe Golf Course",
    latitude: 39.2519,
    longitude: -119.9727,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Napa",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "Silverado Resort North Course",
    latitude: 38.3485,
    longitude: -122.2611,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Jackson",
    locationCountry: "United States",
    locationRegion: "Mississippi",
    venueName: "Country Club of Jackson",
    latitude: 32.2988,
    longitude: -90.1848,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Las Vegas",
    locationCountry: "United States",
    locationRegion: "Nevada",
    venueName: "TPC Summerlin",
    latitude: 36.1699,
    longitude: -115.3338,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Chiba",
    locationCountry: "Japan",
    venueName: "Accordia Golf Narashino Country Club",
    latitude: 35.6073,
    longitude: 140.1063,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Hamilton",
    locationCountry: "United Kingdom",
    locationRegion: "Bermuda",
    venueName: "Port Royal Golf Course",
    latitude: 32.2949,
    longitude: -64.781,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Ivins",
    locationCountry: "United States",
    locationRegion: "Utah",
    venueName: "Black Desert Resort",
    latitude: 37.1686,
    longitude: -113.6794,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Los Cabos",
    locationCountry: "Mexico",
    venueName: "El Cardonal at Diamante",
    latitude: 22.8905,
    longitude: -109.9167,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Sea Island",
    locationCountry: "United States",
    locationRegion: "Georgia",
    venueName: "Sea Island Plantation Course",
    latitude: 31.2274,
    longitude: -81.3532,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
] as const;
