import {
  DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  type GolfVenueSeedEntry,
} from "./golf-venue-types";

/** Rotation-pool alternates — not tied to a fixed annual calendar stop. Merged when golf tour catalogs seed. */
export const GOLF_ROTATION_VENUE_SEED_DATA: readonly GolfVenueSeedEntry[] = [
  {
    locationName: "Louisville",
    locationCountry: "United States",
    locationRegion: "Kentucky",
    venueName: "Valhalla Golf Club",
    latitude: 38.2567,
    longitude: -85.6183,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Tulsa",
    locationCountry: "United States",
    locationRegion: "Oklahoma",
    venueName: "Southern Hills Country Club",
    latitude: 36.0856,
    longitude: -95.9653,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Bethesda",
    locationCountry: "United States",
    locationRegion: "Maryland",
    venueName: "Congressional Country Club",
    latitude: 39.0186,
    longitude: -77.1194,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "San Francisco",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "TPC Harding Park",
    latitude: 37.7269,
    longitude: -122.4936,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Mamaroneck",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "Winged Foot Golf Club",
    latitude: 40.9848,
    longitude: -73.764,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Erin",
    locationCountry: "United States",
    locationRegion: "Wisconsin",
    venueName: "Erin Hills Golf Course",
    latitude: 43.2672,
    longitude: -88.3697,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "University Place",
    locationCountry: "United States",
    locationRegion: "Washington",
    venueName: "Chambers Bay Golf Course",
    latitude: 47.2006,
    longitude: -122.5668,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Lytham St Annes",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Royal Lytham & St Annes Golf Club",
    latitude: 53.7472,
    longitude: -3.0247,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Gullane",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Muirfield",
    latitude: 56.0411,
    longitude: -2.8186,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Turnberry",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Turnberry Ailsa Course",
    latitude: 55.3194,
    longitude: -4.8394,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Melbourne",
    locationCountry: "Australia",
    venueName: "Royal Melbourne Golf Club",
    latitude: -37.9697,
    longitude: 145.0333,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Sydney",
    locationCountry: "Australia",
    venueName: "The Lakes Golf Club",
    latitude: -33.9658,
    longitude: 151.2278,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Leven",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Dumbarnie Links",
    latitude: 56.205,
    longitude: -2.978,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Aberdeen",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Royal Aberdeen Golf Club",
    latitude: 57.1686,
    longitude: -2.0819,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
] as const;

export const GOLF_ROTATION_VENUE_COUNT = GOLF_ROTATION_VENUE_SEED_DATA.length;
