import {
  DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  type GolfVenueSeedEntry,
} from "./golf-venue-types";

/** LPGA Tour venues (merged into the shared golf venue catalog on LPGA seed). */
export const LPGA_VENUE_SEED_DATA: readonly GolfVenueSeedEntry[] = [
  {
    locationName: "Orlando",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Lake Nona Golf and Country Club",
    latitude: 28.3684,
    longitude: -81.2534,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Bradenton",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Bradenton Country Club",
    latitude: 27.4631,
    longitude: -82.5734,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Pattaya",
    locationCountry: "Thailand",
    venueName: "Siam Country Club Old Course",
    latitude: 12.8986,
    longitude: 100.8967,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Singapore",
    locationCountry: "Singapore",
    venueName: "Sentosa Golf Club Tanjong Course",
    latitude: 1.2494,
    longitude: 103.8303,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Hainan",
    locationCountry: "China",
    venueName: "Jian Lake Blue Bay Golf Club",
    latitude: 18.2528,
    longitude: 109.5119,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Chandler",
    locationCountry: "United States",
    locationRegion: "Arizona",
    venueName: "Whirlwind Golf Club at Wild Horse Pass",
    latitude: 33.2781,
    longitude: -111.9731,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Las Vegas",
    locationCountry: "United States",
    locationRegion: "Nevada",
    venueName: "Shadow Creek Golf Course",
    latitude: 36.1958,
    longitude: -115.2819,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Pacific Palisades",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "El Caballero Country Club",
    latitude: 34.0834,
    longitude: -118.5481,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "The Woodlands",
    locationCountry: "United States",
    locationRegion: "Texas",
    venueName: "The Club at Carlton Woods",
    latitude: 30.1658,
    longitude: -95.4613,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Jersey City",
    locationCountry: "United States",
    locationRegion: "New Jersey",
    venueName: "Liberty National Golf Club",
    latitude: 40.7031,
    longitude: -74.0719,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Playa del Carmen",
    locationCountry: "Mexico",
    venueName: "El Camaleon Golf Course at Mayakoba",
    latitude: 20.6296,
    longitude: -87.0739,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Erin",
    locationCountry: "United States",
    locationRegion: "Wisconsin",
    venueName: "Erin Hills Golf Course",
    latitude: 43.2464,
    longitude: -88.3443,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Galloway",
    locationCountry: "United States",
    locationRegion: "New Jersey",
    venueName: "Seaview Bay Course",
    latitude: 39.4773,
    longitude: -74.4788,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Belmont",
    locationCountry: "United States",
    locationRegion: "Michigan",
    venueName: "Blythefield Country Club",
    latitude: 42.9634,
    longitude: -85.4767,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Frisco",
    locationCountry: "United States",
    locationRegion: "Texas",
    venueName: "Fields Ranch East at PGA Frisco",
    latitude: 33.1507,
    longitude: -96.8236,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Midland",
    locationCountry: "United States",
    locationRegion: "Michigan",
    venueName: "Midland Country Club",
    latitude: 43.6156,
    longitude: -84.2472,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Crans-Montana",
    locationCountry: "Switzerland",
    venueName: "Evian Resort Golf Club",
    latitude: 46.3088,
    longitude: 7.4756,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Troon",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Dundonald Links",
    latitude: 55.5415,
    longitude: -4.6599,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Porthcawl",
    locationCountry: "United Kingdom",
    locationRegion: "Wales",
    venueName: "Royal Porthcawl Golf Club",
    latitude: 51.4787,
    longitude: -3.7058,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Portland",
    locationCountry: "United States",
    locationRegion: "Oregon",
    venueName: "Columbia Edgewater Country Club",
    latitude: 45.5698,
    longitude: -122.6294,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Mississauga",
    locationCountry: "Canada",
    locationRegion: "Ontario",
    venueName: "Mississauga Golf and Country Club",
    latitude: 43.589,
    longitude: -79.6441,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Norton",
    locationCountry: "United States",
    locationRegion: "Massachusetts",
    venueName: "TPC Boston",
    latitude: 41.9687,
    longitude: -71.1862,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Maineville",
    locationCountry: "United States",
    locationRegion: "Ohio",
    venueName: "TPC River's Bend",
    latitude: 39.3151,
    longitude: -84.2208,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Rogers",
    locationCountry: "United States",
    locationRegion: "Arkansas",
    venueName: "Pinnacle Country Club",
    latitude: 36.332,
    longitude: -94.1185,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Ewa Beach",
    locationCountry: "United States",
    locationRegion: "Hawaii",
    venueName: "Hoakalei Country Club",
    latitude: 21.3156,
    longitude: -158.0072,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Shanghai",
    locationCountry: "China",
    venueName: "Qizhong Garden Golf Club",
    latitude: 31.0304,
    longitude: 121.3587,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Busan",
    locationCountry: "South Korea",
    venueName: "Pine Beach Golf Links",
    latitude: 35.1796,
    longitude: 129.0756,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Goyang",
    locationCountry: "South Korea",
    venueName: "New Korea Country Club",
    latitude: 37.6584,
    longitude: 126.832,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Kuala Lumpur",
    locationCountry: "Malaysia",
    venueName: "Kuala Lumpur Golf and Country Club",
    latitude: 3.139,
    longitude: 101.6869,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Shiga",
    locationCountry: "Japan",
    venueName: "Seta Golf Course",
    latitude: 35.0045,
    longitude: 135.8686,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Belleair",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Pelican Golf Club",
    latitude: 27.9353,
    longitude: -82.8062,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
  {
    locationName: "Naples",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Tiburon Golf Club",
    latitude: 26.142,
    longitude: -81.7948,
    teeGroupCount: DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT,
  },
] as const;
