import type { GolfTournamentSeedEntry, GolfTournamentVenueRef } from "./golf-tour-seed.types";
import { DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT } from "./golf-venue-types";

export type LpgaTournamentSeedEntry = GolfTournamentSeedEntry & {
  venues: readonly GolfTournamentVenueRef[];
};

export const LPGA_TOUR_SEED = {
  name: "LPGA Tour",
  abbreviation: "LPGA",
} as const;

export const DEFAULT_LPGA_TEE_GROUP_COUNT = DEFAULT_GOLF_VENUE_TEE_GROUP_COUNT;
export const DEFAULT_LPGA_FIELD_SIZE = 144;

const ranked = (minOfficialWorldGolfRank: number) => ({
  kind: "ranked" as const,
  minOfficialWorldGolfRank,
});

function venue(
  locationName: string,
  locationCountry: string,
  venueName: string,
  locationRegion?: string | null,
): readonly GolfTournamentVenueRef[] {
  return [
    {
      locationName,
      locationCountry,
      locationRegion,
      venueName,
      isDefault: true,
    },
  ];
}

/** 2025 LPGA Tour official calendar (33 events). */
export const LPGA_TOURNAMENT_SEED_DATA: readonly LpgaTournamentSeedEntry[] = [
  {
    slug: "hilton-grand-vacations-tournament-of-champions",
    name: "Hilton Grand Vacations Tournament of Champions",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: {
      kind: "exemptions",
      description: "Prior-year LPGA Tour winners",
      exemptionCodes: ["prior_winner"],
    },
    venueMode: "fixed",
    seasonStartMonth: 1,
    seasonStartDay: 30,
    sortOrder: 1,
    venues: venue("Orlando", "United States", "Lake Nona Golf and Country Club", "Florida"),
  },
  {
    slug: "founders-cup",
    name: "Founders Cup",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 6,
    sortOrder: 2,
    venues: venue("Bradenton", "United States", "Bradenton Country Club", "Florida"),
  },
  {
    slug: "honda-lpga-thailand",
    name: "Honda LPGA Thailand",
    isMajor: false,
    purseUsd: 1_700_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 20,
    sortOrder: 3,
    venues: venue("Pattaya", "Thailand", "Siam Country Club Old Course"),
  },
  {
    slug: "hsbc-womens-world-championship",
    name: "HSBC Women's World Championship",
    isMajor: false,
    purseUsd: 2_400_000,
    entryCriteria: ranked(80),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 27,
    sortOrder: 4,
    venues: venue("Singapore", "Singapore", "Sentosa Golf Club Tanjong Course"),
  },
  {
    slug: "blue-bay-lpga",
    name: "Blue Bay LPGA",
    isMajor: false,
    purseUsd: 2_500_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 6,
    sortOrder: 5,
    venues: venue("Hainan", "China", "Jian Lake Blue Bay Golf Club"),
  },
  {
    slug: "ford-championship",
    name: "Ford Championship",
    isMajor: false,
    purseUsd: 2_250_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 27,
    sortOrder: 6,
    venues: venue(
      "Chandler",
      "United States",
      "Whirlwind Golf Club at Wild Horse Pass",
      "Arizona",
    ),
  },
  {
    slug: "t-mobile-match-play",
    name: "T-Mobile Match Play presented by MGM Rewards",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(64),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 2,
    sortOrder: 7,
    venues: venue("Las Vegas", "United States", "Shadow Creek Golf Course", "Nevada"),
  },
  {
    slug: "jm-eagle-la-championship",
    name: "JM Eagle LA Championship presented by Plastpro",
    isMajor: false,
    purseUsd: 3_750_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 17,
    sortOrder: 8,
    venues: venue(
      "Pacific Palisades",
      "United States",
      "El Caballero Country Club",
      "California",
    ),
  },
  {
    slug: "chevron-championship",
    name: "The Chevron Championship",
    isMajor: true,
    purseUsd: 7_900_000,
    entryCriteria: ranked(80),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 24,
    sortOrder: 9,
    venues: venue(
      "The Woodlands",
      "United States",
      "The Club at Carlton Woods",
      "Texas",
    ),
  },
  {
    slug: "black-desert-championship",
    name: "Black Desert Championship",
    isMajor: false,
    purseUsd: 3_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 1,
    sortOrder: 10,
    venues: venue("Ivins", "United States", "Black Desert Resort", "Utah"),
  },
  {
    slug: "mizuho-americas-open",
    name: "Mizuho Americas Open",
    isMajor: false,
    purseUsd: 3_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 8,
    sortOrder: 11,
    venues: venue(
      "Jersey City",
      "United States",
      "Liberty National Golf Club",
      "New Jersey",
    ),
  },
  {
    slug: "riviera-maya-open",
    name: "Riviera Maya Open",
    isMajor: false,
    purseUsd: 2_500_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 22,
    sortOrder: 12,
    venues: venue(
      "Playa del Carmen",
      "Mexico",
      "El Camaleon Golf Course at Mayakoba",
    ),
  },
  {
    slug: "us-womens-open",
    name: "U.S. Women's Open presented by Ally",
    isMajor: true,
    purseUsd: 12_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 29,
    sortOrder: 13,
    venues: venue("Erin", "United States", "Erin Hills Golf Course", "Wisconsin"),
  },
  {
    slug: "shoprite-lpga-classic",
    name: "ShopRite LPGA Classic presented by Acer",
    isMajor: false,
    purseUsd: 1_750_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 6,
    sortOrder: 14,
    venues: venue("Galloway", "United States", "Seaview Bay Course", "New Jersey"),
  },
  {
    slug: "meijer-lpga-classic",
    name: "Meijer LPGA Classic for Simply Give",
    isMajor: false,
    purseUsd: 3_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 12,
    sortOrder: 15,
    venues: venue("Belmont", "United States", "Blythefield Country Club", "Michigan"),
  },
  {
    slug: "kpmg-womens-pga-championship",
    name: "KPMG Women's PGA Championship",
    isMajor: true,
    purseUsd: 12_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 19,
    sortOrder: 16,
    venues: venue(
      "Frisco",
      "United States",
      "Fields Ranch East at PGA Frisco",
      "Texas",
    ),
  },
  {
    slug: "dow-championship",
    name: "Dow Championship",
    isMajor: false,
    purseUsd: 3_300_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 26,
    sortOrder: 17,
    venues: venue("Midland", "United States", "Midland Country Club", "Michigan"),
  },
  {
    slug: "amundi-evian-championship",
    name: "The Amundi Evian Championship",
    isMajor: true,
    purseUsd: 8_000_000,
    entryCriteria: ranked(80),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 10,
    sortOrder: 18,
    venues: venue("Crans-Montana", "Switzerland", "Evian Resort Golf Club"),
  },
  {
    slug: "isps-handa-womens-scottish-open",
    name: "ISPS Handa Women's Scottish Open",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 24,
    sortOrder: 19,
    venues: venue("Troon", "United Kingdom", "Dundonald Links", "Scotland"),
  },
  {
    slug: "aig-womens-open",
    name: "AIG Women's Open",
    isMajor: true,
    purseUsd: 9_750_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 31,
    sortOrder: 20,
    venues: venue(
      "Porthcawl",
      "United Kingdom",
      "Royal Porthcawl Golf Club",
      "Wales",
    ),
  },
  {
    slug: "portland-classic",
    name: "The Standard Portland Classic",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 14,
    sortOrder: 21,
    venues: venue(
      "Portland",
      "United States",
      "Columbia Edgewater Country Club",
      "Oregon",
    ),
  },
  {
    slug: "cpkc-womens-open",
    name: "CPKC Women's Open",
    isMajor: false,
    purseUsd: 2_600_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 21,
    sortOrder: 22,
    venues: venue(
      "Mississauga",
      "Canada",
      "Mississauga Golf and Country Club",
      "Ontario",
    ),
  },
  {
    slug: "fm-championship",
    name: "FM Championship",
    isMajor: false,
    purseUsd: 4_100_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 28,
    sortOrder: 23,
    venues: venue("Norton", "United States", "TPC Boston", "Massachusetts"),
  },
  {
    slug: "kroger-queen-city-championship",
    name: "Kroger Queen City Championship presented by P&G",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 9,
    seasonStartDay: 11,
    sortOrder: 24,
    venues: venue("Maineville", "United States", "TPC River's Bend", "Ohio"),
  },
  {
    slug: "walmart-nw-arkansas-championship",
    name: "Walmart NW Arkansas Championship presented by P&G",
    isMajor: false,
    purseUsd: 3_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 9,
    seasonStartDay: 19,
    sortOrder: 25,
    venues: venue("Rogers", "United States", "Pinnacle Country Club", "Arkansas"),
  },
  {
    slug: "lotte-championship",
    name: "Lotte Championship presented by Hoakalei",
    isMajor: false,
    purseUsd: 3_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 1,
    sortOrder: 26,
    venues: venue("Ewa Beach", "United States", "Hoakalei Country Club", "Hawaii"),
  },
  {
    slug: "buick-lpga-shanghai",
    name: "Buick LPGA Shanghai",
    isMajor: false,
    purseUsd: 2_200_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 9,
    sortOrder: 27,
    venues: venue("Shanghai", "China", "Qizhong Garden Golf Club"),
  },
  {
    slug: "bmw-ladies-championship",
    name: "BMW Ladies Championship",
    isMajor: false,
    purseUsd: 2_300_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 16,
    sortOrder: 28,
    venues: venue("Busan", "South Korea", "Pine Beach Golf Links"),
  },
  {
    slug: "hanwha-lifeplus-international-crown",
    name: "Hanwha Lifeplus International Crown",
    isMajor: false,
    purseUsd: 2_000_000,
    entryCriteria: {
      kind: "exemptions",
      description: "National team qualification",
      exemptionCodes: ["team_event"],
    },
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 23,
    sortOrder: 29,
    venues: venue("Goyang", "South Korea", "New Korea Country Club"),
  },
  {
    slug: "maybank-championship",
    name: "Maybank Championship",
    isMajor: false,
    purseUsd: 3_000_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 30,
    sortOrder: 30,
    venues: venue("Kuala Lumpur", "Malaysia", "Kuala Lumpur Golf and Country Club"),
  },
  {
    slug: "toto-japan-classic",
    name: "Toto Japan Classic",
    isMajor: false,
    purseUsd: 2_100_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 11,
    seasonStartDay: 6,
    sortOrder: 31,
    venues: venue("Shiga", "Japan", "Seta Golf Course"),
  },
  {
    slug: "annika-driven-by-gainbridge",
    name: "The Annika driven by Gainbridge at Pelican",
    isMajor: false,
    purseUsd: 3_250_000,
    entryCriteria: ranked(200),
    venueMode: "fixed",
    seasonStartMonth: 11,
    seasonStartDay: 13,
    sortOrder: 32,
    venues: venue("Belleair", "United States", "Pelican Golf Club", "Florida"),
  },
  {
    slug: "cme-group-tour-championship",
    name: "CME Group Tour Championship",
    isMajor: false,
    purseUsd: 11_000_000,
    entryCriteria: ranked(60),
    venueMode: "fixed",
    seasonStartMonth: 11,
    seasonStartDay: 20,
    sortOrder: 33,
    venues: venue("Naples", "United States", "Tiburon Golf Club", "Florida"),
  },
] as const;
