import type { TennisVenueSeedEntry } from "./tennis-venue-types";

/** Professional tennis multi_resource venues (courts). */
export const TENNIS_VENUE_SEED_DATA: readonly TennisVenueSeedEntry[] = [
  // Grand Slams
  {
    locationName: "New York",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "USTA Billie Jean King National Tennis Center",
    latitude: 40.7498,
    longitude: -73.8456,
    courtCount: 22,
  },
  {
    locationName: "London",
    locationCountry: "United Kingdom",
    venueName: "All England Lawn Tennis and Croquet Club",
    latitude: 51.4344,
    longitude: -0.2142,
    courtCount: 18,
  },
  {
    locationName: "Paris",
    locationCountry: "France",
    venueName: "Stade Roland Garros",
    latitude: 48.8472,
    longitude: 2.2531,
    courtCount: 20,
  },
  {
    locationName: "Melbourne",
    locationCountry: "Australia",
    venueName: "Melbourne Park",
    latitude: -37.8212,
    longitude: 144.9788,
    courtCount: 24,
  },

  // Masters 1000 and premier tour stops (tennis-golf supplemental cities)
  {
    locationName: "Indian Wells",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "Indian Wells Tennis Garden",
    latitude: 33.7242,
    longitude: -116.3269,
    courtCount: 29,
  },
  {
    locationName: "Monte Carlo",
    locationCountry: "Monaco",
    venueName: "Monte Carlo Country Club",
    latitude: 43.7481,
    longitude: 7.4297,
    courtCount: 11,
  },
  {
    locationName: "Rotterdam",
    locationCountry: "Netherlands",
    venueName: "Ahoy Rotterdam",
    latitude: 51.8892,
    longitude: 4.4878,
    courtCount: 8,
  },
  {
    locationName: "Acapulco",
    locationCountry: "Mexico",
    venueName: "Arena GNP Seguros",
    latitude: 16.7573,
    longitude: -99.7541,
    courtCount: 6,
  },
  {
    locationName: "Hamburg",
    locationCountry: "Germany",
    venueName: "Am Rothenbaum",
    latitude: 53.5732,
    longitude: 9.9881,
    courtCount: 12,
  },
  {
    locationName: "Basel",
    locationCountry: "Switzerland",
    venueName: "St. Jakobshalle",
    latitude: 47.5422,
    longitude: 7.6206,
    courtCount: 8,
  },
  {
    locationName: "Eastbourne",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Devonshire Park Lawn Tennis Club",
    latitude: 50.7689,
    longitude: 0.2847,
    courtCount: 8,
  },
  {
    locationName: "Halle",
    locationCountry: "Germany",
    venueName: "OWL Arena",
    latitude: 52.0598,
    longitude: 8.3569,
    courtCount: 10,
  },
  {
    locationName: "Stuttgart",
    locationCountry: "Germany",
    venueName: "Porsche Arena",
    latitude: 48.7925,
    longitude: 9.232,
    courtCount: 10,
  },
  {
    locationName: "Geneva",
    locationCountry: "Switzerland",
    venueName: "Tennis Club de Geneve",
    latitude: 46.2041,
    longitude: 6.145,
    courtCount: 7,
  },
  {
    locationName: "Bad Homburg",
    locationCountry: "Germany",
    venueName: "Tennis Club Bad Homburg",
    latitude: 50.2265,
    longitude: 8.6189,
    courtCount: 8,
  },
  {
    locationName: "Adelaide",
    locationCountry: "Australia",
    venueName: "Memorial Drive Tennis Centre",
    latitude: -34.9186,
    longitude: 138.5962,
    courtCount: 10,
  },
  {
    locationName: "Delray Beach",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Delray Beach Tennis Center",
    latitude: 26.4617,
    longitude: -80.0725,
    courtCount: 8,
  },
  {
    locationName: "Los Cabos",
    locationCountry: "Mexico",
    venueName: "Los Cabos Tennis Open Venue",
    latitude: 22.8905,
    longitude: -109.9167,
    courtCount: 6,
  },
  {
    locationName: "Wuhan",
    locationCountry: "China",
    venueName: "Optics Valley International Tennis Center",
    latitude: 30.4738,
    longitude: 114.4612,
    courtCount: 12,
  },
  {
    locationName: "Zhuhai",
    locationCountry: "China",
    venueName: "Hengqin International Tennis Center",
    latitude: 22.1356,
    longitude: 113.5439,
    courtCount: 6,
  },
  {
    locationName: "Estoril",
    locationCountry: "Portugal",
    venueName: "Estoril Court Central",
    latitude: 38.7059,
    longitude: -9.3972,
    courtCount: 7,
  },
  {
    locationName: "Bastad",
    locationCountry: "Sweden",
    venueName: "Bastad Tennis Stadium",
    latitude: 56.4299,
    longitude: 12.8495,
    courtCount: 6,
  },
  {
    locationName: "Kitzbuhel",
    locationCountry: "Austria",
    venueName: "Kitzbuhel Tennis Stadium",
    latitude: 47.4464,
    longitude: 12.3922,
    courtCount: 4,
  },
  {
    locationName: "Newport",
    locationCountry: "United States",
    locationRegion: "Rhode Island",
    venueName: "International Tennis Hall of Fame",
    latitude: 41.4901,
    longitude: -71.3128,
    courtCount: 7,
  },
  {
    locationName: "Antalya",
    locationCountry: "Turkey",
    venueName: "Antalya Tennis Center",
    latitude: 36.8969,
    longitude: 30.7133,
    courtCount: 6,
  },

  // Additional Masters 1000 staples (major metros in world catalog)
  {
    locationName: "Miami",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Hard Rock Stadium Tennis Center",
    latitude: 25.958,
    longitude: -80.2389,
    courtCount: 16,
  },
  {
    locationName: "Cincinnati",
    locationCountry: "United States",
    locationRegion: "Ohio",
    venueName: "Lindner Family Tennis Center",
    latitude: 39.3481,
    longitude: -84.2753,
    courtCount: 16,
  },
  {
    locationName: "Rome",
    locationCountry: "Italy",
    venueName: "Foro Italico",
    latitude: 41.9319,
    longitude: 12.4572,
    courtCount: 16,
  },
  {
    locationName: "Madrid",
    locationCountry: "Spain",
    venueName: "Caja Magica",
    latitude: 40.3695,
    longitude: -3.6883,
    courtCount: 16,
  },
  {
    locationName: "Shanghai",
    locationCountry: "China",
    venueName: "Qizhong Forest Sports City Arena",
    latitude: 31.0236,
    longitude: 121.3561,
    courtCount: 16,
  },
  {
    locationName: "Beijing",
    locationCountry: "China",
    venueName: "National Tennis Center",
    latitude: 40.0242,
    longitude: 116.3747,
    courtCount: 16,
  },
  {
    locationName: "Montreal",
    locationCountry: "Canada",
    venueName: "IGA Stadium",
    latitude: 45.5319,
    longitude: -73.6272,
    courtCount: 12,
  },
  {
    locationName: "Toronto",
    locationCountry: "Canada",
    venueName: "Aviva Centre",
    latitude: 43.7699,
    longitude: -79.5119,
    courtCount: 12,
  }
] as const;
