import type { TennisGolfVenueSeedEntry } from "./tennis-golf-venue-types";

/**
 * Tennis and golf venues for multi_resource scheduling.
 * Grand Slams use cities from the main world catalog; tour stops use
 * tennis-golf supplemental cities and selected major metros.
 */
export const TENNIS_GOLF_VENUE_SEED_DATA: readonly TennisGolfVenueSeedEntry[] = [
  // Grand Slams
  {
    kind: "tennis",
    locationName: "New York",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "USTA Billie Jean King National Tennis Center",
    latitude: 40.7498,
    longitude: -73.8456,
    courtCount: 22,
  },
  {
    kind: "tennis",
    locationName: "London",
    locationCountry: "United Kingdom",
    venueName: "All England Lawn Tennis and Croquet Club",
    latitude: 51.4344,
    longitude: -0.2142,
    courtCount: 18,
  },
  {
    kind: "tennis",
    locationName: "Paris",
    locationCountry: "France",
    venueName: "Stade Roland Garros",
    latitude: 48.8472,
    longitude: 2.2531,
    courtCount: 20,
  },
  {
    kind: "tennis",
    locationName: "Melbourne",
    locationCountry: "Australia",
    venueName: "Melbourne Park",
    latitude: -37.8212,
    longitude: 144.9788,
    courtCount: 24,
  },

  // Masters 1000 and premier tour stops (tennis-golf supplemental cities)
  {
    kind: "tennis",
    locationName: "Indian Wells",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "Indian Wells Tennis Garden",
    latitude: 33.7242,
    longitude: -116.3269,
    courtCount: 29,
  },
  {
    kind: "tennis",
    locationName: "Monte Carlo",
    locationCountry: "Monaco",
    venueName: "Monte Carlo Country Club",
    latitude: 43.7481,
    longitude: 7.4297,
    courtCount: 11,
  },
  {
    kind: "tennis",
    locationName: "Rotterdam",
    locationCountry: "Netherlands",
    venueName: "Ahoy Rotterdam",
    latitude: 51.8892,
    longitude: 4.4878,
    courtCount: 8,
  },
  {
    kind: "tennis",
    locationName: "Acapulco",
    locationCountry: "Mexico",
    venueName: "Arena GNP Seguros",
    latitude: 16.7573,
    longitude: -99.7541,
    courtCount: 6,
  },
  {
    kind: "tennis",
    locationName: "Hamburg",
    locationCountry: "Germany",
    venueName: "Am Rothenbaum",
    latitude: 53.5732,
    longitude: 9.9881,
    courtCount: 12,
  },
  {
    kind: "tennis",
    locationName: "Basel",
    locationCountry: "Switzerland",
    venueName: "St. Jakobshalle",
    latitude: 47.5422,
    longitude: 7.6206,
    courtCount: 8,
  },
  {
    kind: "tennis",
    locationName: "Eastbourne",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Devonshire Park Lawn Tennis Club",
    latitude: 50.7689,
    longitude: 0.2847,
    courtCount: 8,
  },
  {
    kind: "tennis",
    locationName: "Halle",
    locationCountry: "Germany",
    venueName: "OWL Arena",
    latitude: 52.0598,
    longitude: 8.3569,
    courtCount: 10,
  },
  {
    kind: "tennis",
    locationName: "Stuttgart",
    locationCountry: "Germany",
    venueName: "Porsche Arena",
    latitude: 48.7925,
    longitude: 9.232,
    courtCount: 10,
  },
  {
    kind: "tennis",
    locationName: "Geneva",
    locationCountry: "Switzerland",
    venueName: "Tennis Club de Geneve",
    latitude: 46.2041,
    longitude: 6.145,
    courtCount: 7,
  },
  {
    kind: "tennis",
    locationName: "Bad Homburg",
    locationCountry: "Germany",
    venueName: "Tennis Club Bad Homburg",
    latitude: 50.2265,
    longitude: 8.6189,
    courtCount: 8,
  },
  {
    kind: "tennis",
    locationName: "Adelaide",
    locationCountry: "Australia",
    venueName: "Memorial Drive Tennis Centre",
    latitude: -34.9186,
    longitude: 138.5962,
    courtCount: 10,
  },
  {
    kind: "tennis",
    locationName: "Delray Beach",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Delray Beach Tennis Center",
    latitude: 26.4617,
    longitude: -80.0725,
    courtCount: 8,
  },
  {
    kind: "tennis",
    locationName: "Los Cabos",
    locationCountry: "Mexico",
    venueName: "Los Cabos Tennis Open Venue",
    latitude: 22.8905,
    longitude: -109.9167,
    courtCount: 6,
  },
  {
    kind: "tennis",
    locationName: "Wuhan",
    locationCountry: "China",
    venueName: "Optics Valley International Tennis Center",
    latitude: 30.4738,
    longitude: 114.4612,
    courtCount: 12,
  },
  {
    kind: "tennis",
    locationName: "Zhuhai",
    locationCountry: "China",
    venueName: "Hengqin International Tennis Center",
    latitude: 22.1356,
    longitude: 113.5439,
    courtCount: 6,
  },
  {
    kind: "tennis",
    locationName: "Estoril",
    locationCountry: "Portugal",
    venueName: "Estoril Court Central",
    latitude: 38.7059,
    longitude: -9.3972,
    courtCount: 7,
  },
  {
    kind: "tennis",
    locationName: "Bastad",
    locationCountry: "Sweden",
    venueName: "Bastad Tennis Stadium",
    latitude: 56.4299,
    longitude: 12.8495,
    courtCount: 6,
  },
  {
    kind: "tennis",
    locationName: "Kitzbuhel",
    locationCountry: "Austria",
    venueName: "Kitzbuhel Tennis Stadium",
    latitude: 47.4464,
    longitude: 12.3922,
    courtCount: 4,
  },
  {
    kind: "tennis",
    locationName: "Newport",
    locationCountry: "United States",
    locationRegion: "Rhode Island",
    venueName: "International Tennis Hall of Fame",
    latitude: 41.4901,
    longitude: -71.3128,
    courtCount: 7,
  },
  {
    kind: "tennis",
    locationName: "Antalya",
    locationCountry: "Turkey",
    venueName: "Antalya Tennis Center",
    latitude: 36.8969,
    longitude: 30.7133,
    courtCount: 6,
  },

  // Additional Masters 1000 staples (major metros in world catalog)
  {
    kind: "tennis",
    locationName: "Miami",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "Hard Rock Stadium Tennis Center",
    latitude: 25.958,
    longitude: -80.2389,
    courtCount: 16,
  },
  {
    kind: "tennis",
    locationName: "Cincinnati",
    locationCountry: "United States",
    locationRegion: "Ohio",
    venueName: "Lindner Family Tennis Center",
    latitude: 39.3481,
    longitude: -84.2753,
    courtCount: 16,
  },
  {
    kind: "tennis",
    locationName: "Rome",
    locationCountry: "Italy",
    venueName: "Foro Italico",
    latitude: 41.9319,
    longitude: 12.4572,
    courtCount: 16,
  },
  {
    kind: "tennis",
    locationName: "Madrid",
    locationCountry: "Spain",
    venueName: "Caja Magica",
    latitude: 40.3695,
    longitude: -3.6883,
    courtCount: 16,
  },
  {
    kind: "tennis",
    locationName: "Shanghai",
    locationCountry: "China",
    venueName: "Qizhong Forest Sports City Arena",
    latitude: 31.0236,
    longitude: 121.3561,
    courtCount: 16,
  },
  {
    kind: "tennis",
    locationName: "Beijing",
    locationCountry: "China",
    venueName: "National Tennis Center",
    latitude: 40.0242,
    longitude: 116.3747,
    courtCount: 16,
  },
  {
    kind: "tennis",
    locationName: "Montreal",
    locationCountry: "Canada",
    venueName: "IGA Stadium",
    latitude: 45.5319,
    longitude: -73.6272,
    courtCount: 12,
  },
  {
    kind: "tennis",
    locationName: "Toronto",
    locationCountry: "Canada",
    venueName: "Aviva Centre",
    latitude: 43.7699,
    longitude: -79.5119,
    courtCount: 12,
  },

  // Golf majors and flagship courses (full 30-group field)
  {
    kind: "golf",
    locationName: "Augusta",
    locationCountry: "United States",
    locationRegion: "Georgia",
    venueName: "Augusta National Golf Club",
    latitude: 33.5021,
    longitude: -82.0228,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Pinehurst",
    locationCountry: "United States",
    locationRegion: "North Carolina",
    venueName: "Pinehurst No. 2",
    latitude: 35.1954,
    longitude: -79.4695,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Pebble Beach",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "Pebble Beach Golf Links",
    latitude: 36.5674,
    longitude: -121.9487,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Ponte Vedra Beach",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "TPC Sawgrass",
    latitude: 30.1975,
    longitude: -81.3859,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Palm Beach Gardens",
    locationCountry: "United States",
    locationRegion: "Florida",
    venueName: "PGA National Champion Course",
    latitude: 26.8234,
    longitude: -80.1386,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "La Quinta",
    locationCountry: "United States",
    locationRegion: "California",
    venueName: "PGA West Stadium Course",
    latitude: 33.6634,
    longitude: -116.278,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Lahaina",
    locationCountry: "United States",
    locationRegion: "Hawaii",
    venueName: "Kapalua Plantation Course",
    latitude: 20.9983,
    longitude: -156.6542,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Scottsdale",
    locationCountry: "United States",
    locationRegion: "Arizona",
    venueName: "TPC Scottsdale Stadium Course",
    latitude: 33.6424,
    longitude: -111.9085,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Brookline",
    locationCountry: "United States",
    locationRegion: "Massachusetts",
    venueName: "The Country Club",
    latitude: 42.3318,
    longitude: -71.1212,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Southampton",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "Shinnecock Hills Golf Club",
    latitude: 40.8843,
    longitude: -72.3895,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Oakmont",
    locationCountry: "United States",
    locationRegion: "Pennsylvania",
    venueName: "Oakmont Country Club",
    latitude: 40.5217,
    longitude: -79.8417,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Kiawah Island",
    locationCountry: "United States",
    locationRegion: "South Carolina",
    venueName: "Kiawah Island Ocean Course",
    latitude: 32.6082,
    longitude: -80.0848,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Rochester",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "Oak Hill Country Club",
    latitude: 43.1566,
    longitude: -77.6088,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Farmingdale",
    locationCountry: "United States",
    locationRegion: "New York",
    venueName: "Bethpage Black Course",
    latitude: 40.7446,
    longitude: -73.4658,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Sheboygan",
    locationCountry: "United States",
    locationRegion: "Wisconsin",
    venueName: "Whistling Straits",
    latitude: 43.8436,
    longitude: -87.7308,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "St Andrews",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "St Andrews Old Course",
    latitude: 56.3398,
    longitude: -2.7967,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Troon",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Royal Troon Golf Club",
    latitude: 55.5415,
    longitude: -4.6599,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Carnoustie",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Carnoustie Golf Links",
    latitude: 56.5026,
    longitude: -2.7059,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Gullane",
    locationCountry: "United Kingdom",
    locationRegion: "Scotland",
    venueName: "Gullane Golf Club No. 1",
    latitude: 56.035,
    longitude: -2.8284,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Southport",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Royal Birkdale Golf Club",
    latitude: 53.6476,
    longitude: -3.0053,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Hoylake",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Royal Liverpool Golf Club",
    latitude: 53.3908,
    longitude: -3.1806,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Sandwich",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Royal St George's Golf Club",
    latitude: 51.272,
    longitude: 1.3378,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Wentworth",
    locationCountry: "United Kingdom",
    locationRegion: "England",
    venueName: "Wentworth Club West Course",
    latitude: 51.383,
    longitude: -0.663,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Portrush",
    locationCountry: "United Kingdom",
    locationRegion: "Northern Ireland",
    venueName: "Royal Portrush Dunluce Links",
    latitude: 55.1958,
    longitude: -6.6533,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Crans-Montana",
    locationCountry: "Switzerland",
    venueName: "Crans-sur-Sierre Golf Club",
    latitude: 46.3088,
    longitude: 7.4756,
    teeGroupCount: 30,
  },
  {
    kind: "golf",
    locationName: "Adare",
    locationCountry: "Ireland",
    venueName: "Adare Manor Golf Club",
    latitude: 52.5642,
    longitude: -8.7909,
    teeGroupCount: 30,
  },
] as const;
