import type {
  TennisTournamentSeedEntry,
  TennisTournamentVenueRef,
} from "./tennis-tour-seed.types";

type WtaTournamentVenueRef = TennisTournamentVenueRef;

type WtaTournamentSeedEntry = TennisTournamentSeedEntry & {
  venues: readonly WtaTournamentVenueRef[];
};

const DEFAULT_WTA_ACTIVE_COURT_COUNT = 12;

type WtaTournamentVenueRef = TennisTournamentVenueRef;

type WtaTournamentSeedEntry = TennisTournamentSeedEntry & {
  venues: readonly WtaTournamentVenueRef[];
};

const WTA_1000 = {
  typicalDurationDays: 10,
  activeCourtCount: 14,
  drawSize: 96,
} as const;

const WTA_500 = {
  typicalDurationDays: 7,
  activeCourtCount: DEFAULT_WTA_ACTIVE_COURT_COUNT,
  drawSize: 48,
} as const;

const WTA_250 = {
  typicalDurationDays: 7,
  activeCourtCount: 8,
  drawSize: 28,
} as const;

const ranked = (minWtaRank: number) => ({
  kind: "ranked" as const,
  minWtaRank,
});

const atpReference = (tournamentSlug: string) => ({
  scheduleReference: {
    tourAbbreviation: "ATP",
    tournamentSlug,
  },
});

function venue(
  locationName: string,
  locationCountry: string,
  venueName: string,
  locationRegion?: string | null,
): readonly WtaTournamentVenueRef[] {
  return [
    {
      locationName,
      locationCountry,
      locationRegion,
      venueName,
      isDefault: true,
    },
  ];
}

/** Phase 4 — joint Masters/slams (ATP tree) plus WTA-only venue weeks. */
export const WTA_TOUR_CATALOG_SEED_DATA: readonly WtaTournamentSeedEntry[] = [
  {
    slug: "adelaide-international",
    name: "Adelaide International",
    isMajor: false,
    prizeMoneyUsd: 650_000,
    entryCriteria: ranked(100),
    venueMode: "fixed",
    seasonStartMonth: 1,
    seasonStartDay: 5,
    sortOrder: 5,
    ...WTA_250,
    ...atpReference("adelaide-international"),
    venues: venue("Adelaide", "Australia", "Memorial Drive Tennis Centre"),
  },
  {
    slug: "acapulco-open",
    name: "Abierto Mexicano Telcel",
    isMajor: false,
    prizeMoneyUsd: 2_200_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 2,
    seasonStartDay: 24,
    sortOrder: 6,
    ...WTA_500,
    activeCourtCount: 6,
    ...atpReference("acapulco-open"),
    venues: venue("Acapulco", "Mexico", "Arena GNP Seguros"),
  },
  {
    slug: "indian-wells",
    name: "BNP Paribas Open",
    isMajor: false,
    prizeMoneyUsd: 9_000_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 5,
    sortOrder: 7,
    ...WTA_1000,
    ...atpReference("indian-wells"),
    venues: venue(
      "Indian Wells",
      "United States",
      "Indian Wells Tennis Garden",
      "California",
    ),
  },
  {
    slug: "miami-open",
    name: "Miami Open",
    isMajor: false,
    prizeMoneyUsd: 8_800_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 3,
    seasonStartDay: 19,
    sortOrder: 8,
    ...WTA_1000,
    ...atpReference("miami-open"),
    venues: venue(
      "Miami",
      "United States",
      "Hard Rock Stadium Tennis Center",
      "Florida",
    ),
  },
  {
    slug: "stuttgart-ladies-open",
    name: "Porsche Tennis Grand Prix",
    isMajor: false,
    prizeMoneyUsd: 900_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 14,
    sortOrder: 9,
    ...WTA_500,
    activeCourtCount: 10,
    venues: venue("Stuttgart", "Germany", "Porsche Arena"),
  },
  {
    slug: "madrid-open",
    name: "Mutua Madrid Open",
    isMajor: false,
    prizeMoneyUsd: 8_800_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 23,
    sortOrder: 10,
    ...WTA_1000,
    ...atpReference("madrid-open"),
    venues: venue("Madrid", "Spain", "Caja Magica"),
  },
  {
    slug: "rome-masters",
    name: "Internazionali BNL d'Italia",
    isMajor: false,
    prizeMoneyUsd: 7_800_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 7,
    sortOrder: 11,
    ...WTA_1000,
    ...atpReference("rome-masters"),
    venues: venue("Rome", "Italy", "Foro Italico"),
  },
  {
    slug: "wta-estoril-open",
    name: "Billie Jean King Cup Estoril",
    isMajor: false,
    prizeMoneyUsd: 280_000,
    entryCriteria: ranked(150),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 13,
    sortOrder: 12,
    ...WTA_250,
    activeCourtCount: 7,
    venues: venue("Estoril", "Portugal", "Estoril Court Central"),
  },
  {
    slug: "bad-homburg-open",
    name: "Bad Homburg Open",
    isMajor: false,
    prizeMoneyUsd: 780_000,
    entryCriteria: ranked(75),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 23,
    sortOrder: 13,
    ...WTA_500,
    activeCourtCount: 8,
    venues: venue("Bad Homburg", "Germany", "Tennis Club Bad Homburg"),
  },
  {
    slug: "eastbourne-open",
    name: "Eastbourne International",
    isMajor: false,
    prizeMoneyUsd: 850_000,
    entryCriteria: ranked(75),
    venueMode: "fixed",
    seasonStartMonth: 6,
    seasonStartDay: 23,
    sortOrder: 14,
    ...WTA_250,
    ...atpReference("eastbourne-open"),
    venues: venue(
      "Eastbourne",
      "United Kingdom",
      "Devonshire Park Lawn Tennis Club",
      "England",
    ),
  },
  {
    slug: "wta-bastad-open",
    name: "Nordea Open",
    isMajor: false,
    prizeMoneyUsd: 280_000,
    entryCriteria: ranked(150),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 7,
    sortOrder: 15,
    ...WTA_250,
    activeCourtCount: 6,
    venues: venue("Bastad", "Sweden", "Bastad Tennis Stadium"),
  },
  {
    slug: "wta-hamburg-open",
    name: "Hamburg European Open",
    isMajor: false,
    prizeMoneyUsd: 280_000,
    entryCriteria: ranked(150),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 14,
    sortOrder: 16,
    ...WTA_250,
    venues: venue("Hamburg", "Germany", "Am Rothenbaum"),
  },
  {
    slug: "canadian-open",
    name: "National Bank Open",
    isMajor: false,
    prizeMoneyUsd: 6_500_000,
    entryCriteria: ranked(50),
    venueMode: "rotation",
    seasonStartMonth: 8,
    seasonStartDay: 4,
    rotationEpochYear: 2024,
    sortOrder: 17,
    ...WTA_1000,
    activeCourtCount: 12,
    ...atpReference("canadian-open"),
    venues: [
      {
        locationName: "Toronto",
        locationCountry: "Canada",
        venueName: "Aviva Centre",
        rotationOrder: 0,
        isDefault: true,
      },
      {
        locationName: "Montreal",
        locationCountry: "Canada",
        venueName: "IGA Stadium",
        rotationOrder: 1,
      },
    ],
  },
  {
    slug: "cincinnati-masters",
    name: "Cincinnati Open",
    isMajor: false,
    prizeMoneyUsd: 6_800_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 8,
    seasonStartDay: 11,
    sortOrder: 18,
    ...WTA_1000,
    ...atpReference("cincinnati-masters"),
    venues: venue(
      "Cincinnati",
      "United States",
      "Lindner Family Tennis Center",
      "Ohio",
    ),
  },
  {
    slug: "beijing-china-open",
    name: "China Open",
    isMajor: false,
    prizeMoneyUsd: 8_500_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 9,
    seasonStartDay: 25,
    sortOrder: 19,
    ...WTA_1000,
    venues: venue("Beijing", "China", "National Tennis Center"),
  },
  {
    slug: "wuhan-open",
    name: "Wuhan Open",
    isMajor: false,
    prizeMoneyUsd: 2_200_000,
    entryCriteria: ranked(50),
    venueMode: "fixed",
    seasonStartMonth: 10,
    seasonStartDay: 6,
    sortOrder: 20,
    ...WTA_1000,
    activeCourtCount: 12,
    venues: venue("Wuhan", "China", "Optics Valley International Tennis Center"),
  },
  {
    slug: "geneva-open",
    name: "Geneva Open",
    isMajor: false,
    prizeMoneyUsd: 280_000,
    entryCriteria: ranked(150),
    venueMode: "fixed",
    seasonStartMonth: 5,
    seasonStartDay: 18,
    sortOrder: 21,
    ...WTA_250,
    ...atpReference("geneva-open"),
    venues: venue("Geneva", "Switzerland", "Tennis Club de Geneve"),
  },
  {
    slug: "wta-delray-beach-open",
    name: "Delray Beach Open",
    isMajor: false,
    prizeMoneyUsd: 280_000,
    entryCriteria: ranked(150),
    venueMode: "fixed",
    seasonStartMonth: 1,
    seasonStartDay: 27,
    sortOrder: 22,
    ...WTA_250,
    venues: venue(
      "Delray Beach",
      "United States",
      "Delray Beach Tennis Center",
      "Florida",
    ),
  },
  {
    slug: "antalya-open",
    name: "Antalya Open",
    isMajor: false,
    prizeMoneyUsd: 280_000,
    entryCriteria: ranked(150),
    venueMode: "fixed",
    seasonStartMonth: 4,
    seasonStartDay: 6,
    sortOrder: 23,
    ...WTA_250,
    activeCourtCount: 6,
    venues: venue("Antalya", "Turkey", "Antalya Tennis Center"),
  },
  {
    slug: "zhuhai-open",
    name: "WTA Elite Trophy Zhuhai",
    isMajor: false,
    prizeMoneyUsd: 2_500_000,
    entryCriteria: ranked(20),
    venueMode: "fixed",
    seasonStartMonth: 11,
    seasonStartDay: 3,
    sortOrder: 24,
    ...WTA_500,
    activeCourtCount: 6,
    venues: venue("Zhuhai", "China", "Hengqin International Tennis Center"),
  },
  {
    slug: "wta-kitzbuhel-open",
    name: "Ladies Open Kitzbuhel",
    isMajor: false,
    prizeMoneyUsd: 280_000,
    entryCriteria: ranked(150),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 28,
    sortOrder: 25,
    ...WTA_250,
    activeCourtCount: 4,
    venues: venue("Kitzbuhel", "Austria", "Kitzbuhel Tennis Stadium"),
  },
  {
    slug: "wta-newport-open",
    name: "Hall of Fame Open",
    isMajor: false,
    prizeMoneyUsd: 280_000,
    entryCriteria: ranked(150),
    venueMode: "fixed",
    seasonStartMonth: 7,
    seasonStartDay: 14,
    sortOrder: 26,
    ...WTA_250,
    activeCourtCount: 7,
    venues: venue(
      "Newport",
      "United States",
      "International Tennis Hall of Fame",
      "Rhode Island",
    ),
  },
] as const;

export const WTA_TOUR_CATALOG_EXPECTED = {
  jointWithAtpCount: 10,
  wtaOnlyCount: 12,
  wta1000Count: 8,
} as const;
