export class EventError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "EventError";
    this.code = code;
  }
}

export const EventErrorCodes = {
  INVALID_ACTION: "INVALID_ACTION",
  INVALID_NAME: "INVALID_NAME",
  INVALID_ID: "INVALID_ID",
  MISSING_ID: "MISSING_ID",
  MISSING_VENUE_ID: "MISSING_VENUE_ID",
  INVALID_LOCAL_START: "INVALID_LOCAL_START",
  INVALID_DURATION: "INVALID_DURATION",
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  PARENT_NOT_FOUND: "PARENT_NOT_FOUND",
  PARENT_VENUE_MISMATCH: "PARENT_VENUE_MISMATCH",
  PARENT_TIME_CONTAINMENT: "PARENT_TIME_CONTAINMENT",
  CHILD_TIME_CONTAINMENT: "CHILD_TIME_CONTAINMENT",
  VENUE_SCHEDULE_CONFLICT: "VENUE_SCHEDULE_CONFLICT",
  VENUE_RESOURCE_NOT_ALLOWED: "VENUE_RESOURCE_NOT_ALLOWED",
  VENUE_RESOURCE_NOT_FOUND: "VENUE_RESOURCE_NOT_FOUND",
  VENUE_RESOURCE_VENUE_MISMATCH: "VENUE_RESOURCE_VENUE_MISMATCH",
  EMPTY_UPDATE: "EMPTY_UPDATE",
  VENUE_NOT_FOUND: "VENUE_NOT_FOUND",
  INVALID_ISO_UTC: "INVALID_ISO_UTC",
} as const;
