/**
 * NCAA Division I schools (football + men's basketball) keyed to campus cities
 * in scripts/generate-ncaa-locations.ts (NCAA_CAMPUSES), plus FBS programs
 * in major world-seed cities not listed there.
 *
 * Attendance figures are approximate total enrollment circa 2024.
 */

export type NcaaSchool = readonly [name: string, city: string, state: string, attendance: number];

export const NCAA_SCHOOLS: readonly NcaaSchool[] = [
  // FBS — ACC
  ["Boston College", "Chestnut Hill", "Massachusetts", 15000],
  ["University of California, Berkeley", "Berkeley", "California", 45000],
  ["Clemson University", "Clemson", "South Carolina", 28000],
  ["Duke University", "Durham", "North Carolina", 17000],
  ["Florida State University", "Tallahassee", "Florida", 44000],
  ["University of Louisville", "Louisville", "Kentucky", 23000],
  ["University of North Carolina at Chapel Hill", "Chapel Hill", "North Carolina", 32000],
  ["Stanford University", "Stanford", "California", 17000],
  ["Syracuse University", "Syracuse", "New York", 23000],
  ["University of Virginia", "Charlottesville", "Virginia", 26000],
  ["Virginia Tech", "Blacksburg", "Virginia", 37000],
  ["Wake Forest University", "Winston-Salem", "North Carolina", 9000],

  // FBS — American
  ["United States Military Academy", "West Point", "New York", 4500],
  ["East Carolina University", "Greenville", "North Carolina", 28000],
  ["Florida Atlantic University", "Boca Raton", "Florida", 30000],
  ["United States Naval Academy", "Annapolis", "Maryland", 4500],
  ["University of North Texas", "Denton", "Texas", 44000],
  ["University of Tulsa", "Tulsa", "Oklahoma", 11000],
  ["University of Alabama at Birmingham", "Birmingham", "Alabama", 22000],

  // FBS — Big 12
  ["University of Arizona", "Tucson", "Arizona", 52000],
  ["Arizona State University", "Tempe", "Arizona", 78000],
  ["Baylor University", "Waco", "Texas", 20000],
  ["Brigham Young University", "Provo", "Utah", 34000],
  ["University of Colorado Boulder", "Boulder", "Colorado", 38000],
  ["Iowa State University", "Ames", "Iowa", 32000],
  ["University of Kansas", "Lawrence", "Kansas", 28000],
  ["Kansas State University", "Manhattan", "Kansas", 22000],
  ["Oklahoma State University", "Stillwater", "Oklahoma", 25000],
  ["Texas Christian University", "Fort Worth", "Texas", 12000],
  ["Texas Tech University", "Lubbock", "Texas", 40000],
  ["West Virginia University", "Morgantown", "West Virginia", 26000],

  // FBS — Big Ten
  ["University of Illinois Urbana-Champaign", "Champaign", "Illinois", 56000],
  ["Indiana University Bloomington", "Bloomington", "Indiana", 48000],
  ["University of Iowa", "Iowa City", "Iowa", 33000],
  ["University of Maryland, College Park", "College Park", "Maryland", 41000],
  ["University of Michigan", "Ann Arbor", "Michigan", 48000],
  ["Michigan State University", "East Lansing", "Michigan", 50000],
  ["University of Nebraska-Lincoln", "Lincoln", "Nebraska", 25000],
  ["Northwestern University", "Evanston", "Illinois", 23000],
  ["University of Oregon", "Eugene", "Oregon", 24000],
  ["Pennsylvania State University", "State College", "Pennsylvania", 47000],
  ["Purdue University", "West Lafayette", "Indiana", 52000],
  ["Rutgers University-New Brunswick", "Piscataway", "New Jersey", 68000],
  ["University of Wisconsin-Madison", "Madison", "Wisconsin", 49000],

  // FBS — Conference USA
  ["University of Delaware", "Newark", "Delaware", 24000],
  ["Jacksonville State University", "Jacksonville", "Alabama", 10000],
  ["Kennesaw State University", "Kennesaw", "Georgia", 41000],
  ["Liberty University", "Lynchburg", "Virginia", 15000],
  ["Louisiana Tech University", "Ruston", "Louisiana", 12000],
  ["Middle Tennessee State University", "Murfreesboro", "Tennessee", 22000],
  ["Missouri State University", "Springfield", "Missouri", 24000],
  ["New Mexico State University", "Las Cruces", "New Mexico", 14000],
  ["Sam Houston State University", "Huntsville", "Texas", 22000],
  ["University of Texas at El Paso", "El Paso", "Texas", 24000],
  ["Western Kentucky University", "Bowling Green", "Kentucky", 17000],

  // FBS — Independent
  ["University of Connecticut", "Storrs", "Connecticut", 32000],
  ["University of Notre Dame", "South Bend", "Indiana", 13000],

  // FBS — MAC
  ["University of Akron", "Akron", "Ohio", 16000],
  ["Ball State University", "Muncie", "Indiana", 21000],
  ["Bowling Green State University", "Bowling Green", "Ohio", 18000],
  ["Central Michigan University", "Mount Pleasant", "Michigan", 16000],
  ["Eastern Michigan University", "Ypsilanti", "Michigan", 17000],
  ["Kent State University", "Kent", "Ohio", 28000],
  ["Miami University", "Oxford", "Ohio", 19000],
  ["Northern Illinois University", "DeKalb", "Illinois", 16000],
  ["Ohio University", "Athens", "Ohio", 28000],
  ["University of Toledo", "Toledo", "Ohio", 19000],
  ["University of Massachusetts Amherst", "Amherst", "Massachusetts", 32000],
  ["Western Michigan University", "Kalamazoo", "Michigan", 18000],

  // FBS — Mountain West
  ["United States Air Force Academy", "Colorado Springs", "Colorado", 4400],
  ["Boise State University", "Boise", "Idaho", 28000],
  ["Colorado State University", "Fort Collins", "Colorado", 34000],
  ["California State University, Fresno", "Fresno", "California", 25000],
  ["University of Hawaii at Manoa", "Honolulu", "Hawaii", 18000],
  ["University of Nevada, Reno", "Reno", "Nevada", 21000],
  ["University of New Mexico", "Albuquerque", "New Mexico", 23000],
  ["Utah State University", "Logan", "Utah", 28000],
  ["University of Wyoming", "Laramie", "Wyoming", 12000],

  // FBS — Pac-12
  ["Oregon State University", "Corvallis", "Oregon", 34000],
  ["Washington State University", "Pullman", "Washington", 29000],

  // FBS — SEC
  ["University of Alabama", "Tuscaloosa", "Alabama", 39000],
  ["University of Arkansas", "Fayetteville", "Arkansas", 30000],
  ["Auburn University", "Auburn", "Alabama", 32000],
  ["University of Florida", "Gainesville", "Florida", 55000],
  ["University of Kentucky", "Lexington", "Kentucky", 32000],
  ["Louisiana State University", "Baton Rouge", "Louisiana", 37000],
  ["Mississippi State University", "Starkville", "Mississippi", 23000],
  ["University of Mississippi", "Oxford", "Mississippi", 24000],
  ["University of Missouri", "Columbia", "Missouri", 32000],
  ["University of Oklahoma", "Norman", "Oklahoma", 32000],
  ["University of South Carolina", "Columbia", "South Carolina", 36000],
  ["University of Tennessee, Knoxville", "Knoxville", "Tennessee", 36000],
  ["University of Texas at Austin", "Austin", "Texas", 52000],
  ["Texas A&M University", "College Station", "Texas", 75000],
  ["University of Georgia", "Athens", "Georgia", 41000],

  // FBS — Sun Belt
  ["Appalachian State University", "Boone", "North Carolina", 21000],
  ["Arkansas State University", "Jonesboro", "Arkansas", 14000],
  ["Coastal Carolina University", "Conway", "South Carolina", 11000],
  ["Georgia Southern University", "Statesboro", "Georgia", 27000],
  ["James Madison University", "Harrisonburg", "Virginia", 22000],
  ["University of Louisiana at Lafayette", "Lafayette", "Louisiana", 19000],
  ["Marshall University", "Huntington", "West Virginia", 11000],
  ["Old Dominion University", "Norfolk", "Virginia", 24000],
  ["University of South Alabama", "Mobile", "Alabama", 14000],
  ["University of Southern Mississippi", "Hattiesburg", "Mississippi", 14000],
  ["Texas State University", "San Marcos", "Texas", 38000],
  ["Troy University", "Troy", "Alabama", 16000],
  ["University of Louisiana at Monroe", "Monroe", "Louisiana", 9000],

  // FCS — Big Sky
  ["University of California, Davis", "Davis", "California", 40000],
  ["California Polytechnic State University, San Luis Obispo", "San Luis Obispo", "California", 22000],
  ["Eastern Washington University", "Cheney", "Washington", 12000],
  ["University of Idaho", "Moscow", "Idaho", 11000],
  ["Idaho State University", "Pocatello", "Idaho", 12000],
  ["University of Montana", "Missoula", "Montana", 10000],
  ["Montana State University", "Bozeman", "Montana", 17000],
  ["Northern Arizona University", "Flagstaff", "Arizona", 28000],
  ["University of Northern Colorado", "Greeley", "Colorado", 10000],
  ["Weber State University", "Ogden", "Utah", 29000],

  // FCS — CAA / Patriot / Ivy / MEAC / NEC
  ["Brown University", "Providence", "Rhode Island", 11000],
  ["Cornell University", "Ithaca", "New York", 25000],
  ["Dartmouth College", "Hanover", "New Hampshire", 6800],
  ["Harvard University", "Cambridge", "Massachusetts", 23000],
  ["Princeton University", "Princeton", "New Jersey", 8500],
  ["Yale University", "New Haven", "Connecticut", 15000],
  ["Bethune-Cookman University", "Daytona Beach", "Florida", 2500],
  ["Delaware State University", "Dover", "Delaware", 5000],
  ["South Carolina State University", "Orangeburg", "South Carolina", 3000],
  ["University of Richmond", "Richmond", "Virginia", 4000],
  ["College of William & Mary", "Williamsburg", "Virginia", 9500],
  ["Towson University", "Towson", "Maryland", 22000],
  ["University of Rhode Island", "Kingston", "Rhode Island", 18000],
  ["University of New Hampshire", "Durham", "New Hampshire", 15000],
  ["Bucknell University", "Lewisburg", "Pennsylvania", 3800],
  ["Colgate University", "Hamilton", "New York", 3200],
  ["College of the Holy Cross", "Worcester", "Massachusetts", 3200],
  ["Lafayette College", "Easton", "Pennsylvania", 2600],
  ["Lehigh University", "Bethlehem", "Pennsylvania", 7000],
  ["Marist College", "Poughkeepsie", "New York", 7000],
  ["Campbell University", "Buies Creek", "North Carolina", 6000],
  ["Elon University", "Elon", "North Carolina", 7000],
  ["Monmouth University", "West Long Branch", "New Jersey", 6000],
  ["Hampton University", "Hampton", "Virginia", 4000],
  ["University of Maine", "Orono", "Maine", 12000],
  ["North Carolina Agricultural and Technical State University", "Greensboro", "North Carolina", 13000],
  ["Stony Brook University", "Stony Brook", "New York", 26000],
  ["Sacred Heart University", "Fairfield", "Connecticut", 6000],
  ["Central Connecticut State University", "New Britain", "Connecticut", 11000],
  ["Bryant University", "Smithfield", "Rhode Island", 4000],
  ["Stonehill College", "Easton", "Massachusetts", 3000],
  ["Saint Francis University", "Loretto", "Pennsylvania", 3000],
  ["Long Island University", "Brookville", "New York", 15000],
  ["University at Albany, SUNY", "Albany", "New York", 17000],
  ["Merrimack College", "Merrimack", "Massachusetts", 5000],

  // FCS — Missouri Valley / Big South-OVC
  ["Illinois State University", "Normal", "Illinois", 20000],
  ["Indiana State University", "Terre Haute", "Indiana", 12000],
  ["University of North Dakota", "Grand Forks", "North Dakota", 14000],
  ["North Dakota State University", "Fargo", "North Dakota", 13000],
  ["South Dakota State University", "Brookings", "South Dakota", 12000],
  ["University of South Dakota", "Vermillion", "South Dakota", 10000],
  ["University of Northern Iowa", "Cedar Falls", "Iowa", 10000],
  ["Southern Illinois University Carbondale", "Carbondale", "Illinois", 11000],
  ["Western Illinois University", "Macomb", "Illinois", 8000],
  ["Youngstown State University", "Youngstown", "Ohio", 11000],
  ["Murray State University", "Murray", "Kentucky", 10000],
  ["Morehead State University", "Morehead", "Kentucky", 9000],
  ["Eastern Illinois University", "Charleston", "Illinois", 8000],
  ["Southeast Missouri State University", "Cape Girardeau", "Missouri", 11000],
  ["Tennessee Technological University", "Cookeville", "Tennessee", 10000],
  ["University of Tennessee at Martin", "Martin", "Tennessee", 7000],
  ["Eastern Kentucky University", "Richmond", "Kentucky", 14000],
  ["Gardner-Webb University", "Boiling Springs", "North Carolina", 4000],
  ["Lindenwood University", "St. Charles", "Missouri", 10000],
  ["University of St. Francis", "Romeoville", "Illinois", 4000],

  // FCS — SoCon / Southern / Southland / UAC / SWAC / Pioneer
  ["University of Tennessee at Chattanooga", "Chattanooga", "Tennessee", 12000],
  ["East Tennessee State University", "Johnson City", "Tennessee", 14000],
  ["Furman University", "Greenville", "South Carolina", 3000],
  ["Mercer University", "Macon", "Georgia", 9000],
  ["Wofford College", "Spartanburg", "South Carolina", 1800],
  ["The Citadel", "Charleston", "South Carolina", 3500],
  ["Western Carolina University", "Cullowhee", "North Carolina", 12000],
  ["Washington and Lee University", "Lexington", "Virginia", 1900],
  ["Drake University", "Des Moines", "Iowa", 5000],
  ["Davidson College", "Davidson", "North Carolina", 2000],
  ["University of Dayton", "Dayton", "Ohio", 11000],
  ["Stetson University", "DeLand", "Florida", 4500],
  ["Valparaiso University", "Valparaiso", "Indiana", 4000],
  ["McNeese State University", "Lake Charles", "Louisiana", 7000],
  ["Nicholls State University", "Thibodaux", "Louisiana", 6000],
  ["Northwestern State University of Louisiana", "Natchitoches", "Louisiana", 11000],
  ["Southeastern Louisiana University", "Hammond", "Louisiana", 14000],
  ["Lamar University", "Beaumont", "Texas", 16000],
  ["Alabama State University", "Montgomery", "Alabama", 4000],
  ["Alabama A&M University", "Huntsville", "Alabama", 6000],
  ["Jackson State University", "Jackson", "Mississippi", 7000],
  ["Prairie View A&M University", "Prairie View", "Texas", 9000],
  ["University of North Alabama", "Florence", "Alabama", 8000],
  ["Tarleton State University", "Stephenville", "Texas", 15000],
  ["Utah Tech University", "St. George", "Utah", 12000],
  ["University of West Georgia", "Carrollton", "Georgia", 13000],
  ["Abilene Christian University", "Abilene", "Texas", 6000],
  ["Stephen F. Austin State University", "Nacogdoches", "Texas", 12000],
  ["Texas A&M University-Commerce", "Commerce", "Texas", 12000],
  ["Albany State University", "Albany", "Georgia", 6000],
  ["Alcorn State University", "Lorman", "Mississippi", 3000],
  ["University of Arkansas at Pine Bluff", "Pine Bluff", "Arkansas", 2500],
  ["Grambling State University", "Grambling", "Louisiana", 5000],
  ["University of Central Arkansas", "Conway", "Arkansas", 11000],
  ["University of St. Thomas", "St. Paul", "Minnesota", 10000],

  // FBS — major world-seed cities (not in NCAA_CAMPUSES)
  ["The Ohio State University", "Columbus", "Ohio", 61000],
  ["University of Southern California", "Los Angeles", "California", 48000],
  ["University of California, Los Angeles", "Los Angeles", "California", 46000],
  ["Georgia Institute of Technology", "Atlanta", "Georgia", 44000],
  ["University of Miami", "Coral Gables", "Florida", 19000],
  ["Temple University", "Philadelphia", "Pennsylvania", 37000],
  ["Rice University", "Houston", "Texas", 8000],
  ["University of South Florida", "Tampa", "Florida", 50000],
  ["University of Central Florida", "Orlando", "Florida", 69000],
  ["University of Cincinnati", "Cincinnati", "Ohio", 46000],
  ["University of Houston", "Houston", "Texas", 47000],
  ["University of Utah", "Salt Lake City", "Utah", 35000],
  ["University of Washington", "Seattle", "Washington", 48000],
  ["University of Minnesota Twin Cities", "Minneapolis", "Minnesota", 52000],
  ["University of Pittsburgh", "Pittsburgh", "Pennsylvania", 29000],
  ["Southern Methodist University", "Dallas", "Texas", 12000],
  ["Vanderbilt University", "Nashville", "Tennessee", 13000],
] as const;
